### ISSUE TITLE
cant open file from URL

### ISSUE THREAD

**Issue by anonish** [phillipberndt/pqiv#102]
I was able to open files from URL, primarily through firefox's "open with" extension, but also in terminal as such:
pqiv http://i1-win.softpedia-static.com/screenshots/Nokia-Test-Pattern-Generator_1.png

in firefox I also had it set as 
pqiv -ic [url]
to open a borderless window with no transparency.

now, however, either option yields an error:
Failed to load image http://i1-win.softpedia-static.com/screenshots/Nokia-Test-Pattern-Generator_1.png: Operation not supported
No images left to display.

works when i use feh with same URL (or any URL)
currently on version pqiv-git-2.9.r9.gc951cab (on archlinux)

build shows no errors or missing backends:
Determining executable extension..            (none)
Checking for supported backends..             libav archive_cbx archive poppler webp wand spectre gdkpixbuf
Building with backends:                       libav archive_cbx archive poppler webp wand spectre gdkpixbuf
Checking if the prerequisites are installed.. ok

ffmepg @ 1:3.3.3
curl @ 54.1

am I missing a library somewhere? was working a few days ago

**Comment by phillipberndt** [comment]
When someone else had this problem some time ago we found that the problem
was that gvfs wasn't installed/running. Could you check that it is?!

**Comment by anonish** [comment]
I have
gvfs 1.32.1
gvfs-gphoto2 1.32.1

gvfsd is running and working as far as I can tell

**Comment by phillipberndt** [comment]
Hmm. (I just realized that it was you having problems with this the last time, too, see #86. Sorry for the confusion :))

Does `gvfsd-http` exist & is it running? (It should be started by gvfsd once you try accessing a http(s) resouce.)

What happens if you run `gvfs-cat "https://github.com/phillipberndt/pqiv/issues/102"`?

**Comment by anonish** [comment]
I remember opening that lol
gvfs is compiled with 
HTTP/WebDAV support:          yes

running gvfs-cat:
> gvfs-cat "https://github.com/phillipberndt/pqiv/issues/102"
This tool has been deprecated, use 'gio cat' instead.
See 'gio help cat' for more info.

gio: https://github.com/phillipberndt/pqiv/issues/102: Operation not supported

same with gio cat "https://github.com/phillipberndt/pqiv/issues/102"

**Comment by phillipberndt** [comment]
..then the issue at least definitively isn't in pqiv but in your gio setup: Loading URLs from the command line program should work.

 I suspect that either you are missing the gvfsd-http tool, or the mount file, or that dbus isn't configured correctly.

**Comment by anonish** [comment]
sounds like you're right
gio open "url" opens it in firefox (whether it's an image or not)
thanks, i'll have to hunt down the issue

**Comment by anonish** [comment]
the problem ended up not being gvfs at all, but sddm/lightdm.
in kde (with a DM), pqiv failed to load any external images
in lxde (with DM), I  was able to load external images, so I thought it was kde, but I couldnt figure out what.  On a whim, I tried kde with startkde instead of a DM, and voila, pqiv works with external images once again.  I'll have to dig through the DMs to see what they're doing that prevents gvim from being loaded or if it is loaded, from working. my guess is something to do with polkit and/or dbus.  but it is working now, so I'm happy
