### ISSUE TITLE
Gdk-CRITICAL warning

### ISSUE THREAD

**Issue by chneukirchen** [phillipberndt/pqiv#106]
When running pqiv, I get a:

`(pqiv:14092): Gdk-CRITICAL **: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed`

(using gtk+ 3.22.19)

Does window_show_cursor need a guard to check if window is good?

**Comment by phillipberndt** [comment]
Should be fixed by d3bc7a3.
