### ISSUE TITLE
Most recent build crashes after video plays for 5-10 seconds

### ISSUE THREAD

**Issue by RonCam** [phillipberndt/pqiv#107]
I checked the version in terminal and saw this:
```
~$ pqiv  --version
pqiv 2.9-20-gbc7c4cb-dirty
```
Does the term _dirty_ after the version number indicate something may be wrong?  Or, has something in the program been re-coded to require more resources than the version immediately preceding?

Behavior noticed:  video begins to play, but then freezes into a still image; unresponsive to attempts to terminate program.  It can be 'killed', however, without crashing the operating system.  

System information:
Bodhi Linux (Legacy, 32-bit)
Netbook with 1GB RAM

**Comment by phillipberndt** [comment]
*dirty* means that there are local modifications to your source tree, `git diff` should reveal what they are. Videos work for me, so we'll have to try to debug this on your end.

* Does the [latest Linux nightly version work](https://intern.pberndt.com/pqiv_builds/)? It's a 32bit build as well, but statically linked against the latest FFmpeg release. (If you don't want to blindly execute someone else's binaries you can skip this step for now, we'll figure out what's going out anyway. But this would be a good indicator that there's a dependency issue.)
* Does this affect all or only some video files? For example, [this video works for me](http://mirror.cessen.com/blender.org/peach/trailer/trailer_480p.mov). If only some files are affected, can you share one which is?
* What about animated gif files. Does pqiv crash for those, too?
* Please compile a debug build (add `DEBUG=1` to `config.make` and replace `CFLAGS` to be `-Og -g` in the same file after running `configure` but before running `make`. Make sure to run `make clean` before doing any of this.). Then run the debug build from gdb, `gdb --args ./pqiv <your video file>`, in gdb type `r<enter>` to run. When the program crashes, print a traceback using `tb<enter>` and paste the output.
* Which version of ffmpeg do you have installed?

**Comment by RonCam** [comment]
Thanks very much for the quick reply and your interest in my problem.  Rather than waiting until each of your suggestions has been followed, I'm going to reply with those to which I can answer more quickly -- and then work on the remainder.
> Does this affect all or only some video files? For example, this video works for me. If only some files are affected, can you share one which is?

It affects all files.  I downloaded the one you linked, and it crashed on the opening title.
> What about animated gif files. Does pqiv crash for those, too?

Yes -- not only animated gifs, but even a .jpg file.  There's no motion in a .jpg of course, but I can test it by toggling the 'i' key, to make the yellow bar appear and disappear.  When the yellow bar becomes unresponsive, I take that as meaning the program crashed.  
> Which version of ffmpeg do you have installed?

$ ffmpeg -version
ffmpeg version 2.4.3-1ubuntu1~trusty6 Copyright (c) 2000-2014 the FFmpeg developers
built on Nov 22 2014 17:07:19 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)

Next I will try the nightly build, and then the debugging.

The only other thing -- it could be something I did to my operating system.  Just before this program stopped working, I was attempting to install the _ash_ shell and after several attempts at running an installation script, with nothing happening (at least, not where I was looking), I concluded the directions were incompatible with my directory structure.  Perhaps I damaged something else.

Given that you told me 1) the _dirty_ parameter is not what I thought it was, and that 2)all is working on your end, let me boot my desktop system (LinuxMint 17.3) and try to display the same files, with the same version of _pqiv_.  If that works, perhaps a _System Restore_ on the netbook would be in order, to a date prior to my _ash_ experiments.

Thanks again, and since it's getting late here, I may have to continue tomorrow.

**Comment by phillipberndt** [comment]
I suspect you'll find that the static version and the Mint one will work as expected. But I don't think that this is related to anything ash related either. The last bullet point, run with gdb to generate a backtrace, would probably be most helpful! Also, which desktop environment do you use?

**Comment by RonCam** [comment]
Thanks again for watching this issue.

I am writing this from the desktop LinuxMint system, and to my surprise, the sample video file you supplied 'froze' at just about the same place.  
The netbook is running _Enlightenment 17_ and the desktop is running _KDE_.

Unlike the more basic _Enlightenment_, _KDE_ popped-up a warning while trying to close the _pqiv_ window, saying that the program 'was unresponsive' and gave me the choice to 'kill' it.  

On the desktop system: 
_> ffmpeg -version
ffmpeg version 2.8-1~ trusty+1 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)_

The repeated false-starts in terminal with the failing ash-installer script -- that was on the netbook, only -- so, your opinion that it's not a likely cause is correct.  

Tomorrow I'll continue with installing the nightly build, first, as the last option will have a learning curve since doing what your described will be the first time for me.

**Comment by RonCam** [comment]
I rolled-back the netbook's system files, about 5-6 days, and Synaptic then showed an earlier version of pqiv, the one that was current at that time.  I am almost positive that this installation was working, but both the test video file and static images (gif, jpeg) are now failing, even with the earlier version

I have no idea how or why this could happen.  .

I ran top in terminal and observed running processes as pqiv was launched.  The process appears in the list as soon as pqiv loads and runs, but then disappears from the list, in perhaps 3 seconds.  Pqiv appears to last longer on the screen that the time the process is active, likely because when it aborts, any image pqiv produced remains in video memory and therefore persists on the screen.

I'll next try the nightly build, but with the observed behavior of the older version, I'm wondering if it's really a 'version problem' and not something else on my system, or on both systems -- since the same peculiar behavior is observed on the netbook and desktop, each with its own and different distro.  

May I assume, after running this in terminal:
```
echo "deb http://intern.pberndt.com/pqiv_builds/debian ./" | sudo tee -a /etc/apt/sources.list
	wget -O - https://intern.pberndt.com/pqiv_builds/debian/pubkey.gpg | sudo apt-key add -
```
I will find the nightly in Synaptic?

**Comment by phillipberndt** [comment]
> I rolled-back the netbook's system files, about 5-6 days, and Synaptic then showed an earlier version of pqiv, the one that was current at that time. I am almost positive that this installation was working, but both the test video file and static images (gif, jpeg) are now failing, even with the earlier version

Which apt repository do you use? Debian/Ubuntu/Mint's pqiv package was last updates 12 months ago or so.

> I'll next try the nightly build, but with the observed behavior of the older version, I'm wondering if it's really a 'version problem' and not something else on my system, or on both systems 

Well, it's probably not related to pqiv, but by trying with the static nightly, you can at least tell if its the graphics driver or X11, or one of pqiv's dependencies.

> May I assume, after running this in terminal: [..] I will find the nightly in Synaptic?

Yes, it'll override the *pqiv* package with a git version. But there's no need for that.

    wget http://intern.pberndt.com/pqiv_builds/pqiv-master-2.9-22-g1dcf9cc-static-linux-i386 -O pqiv-nightly
    chmod +x ./pqiv-nightly
    ./pqiv-nightly <files>

will do.

**Comment by phillipberndt** [comment]
..any updates? I'd like to make a new release soon, and it'd be great to resolve this bug before that :-)
