### ISSUE TITLE
Feature request: scale toggle between just two states. 

### ISSUE THREAD

**Issue by magnetophon** [phillipberndt/pqiv#115]
I'd like to pick an auto scale mode in the config file, and toggle between just that and 100%.

**Comment by phillipberndt** [comment]
That's already possible. The key bindings language is very powerful :-) There is an example in the man page, near the end, on how to bind `x` to cycle between 100%, 50% and 25% scale. You should be able to adapt it to your use case readily. Let me know if you need help.

**Comment by magnetophon** [comment]
Ah, yes, found it.
I can make that work, thanks.

**Comment by magnetophon** [comment]
I kind of got it working:
```
t { send_keys(#1); }
  <numbersign>1 { set_scale_level_absolute(1); bind_key(t { send_keys(#2\); }); }
  <numbersign>2 { toggle_scale_mode(5);  bind_key(t { send_keys(#1\); }); 
```
The only problem is that is doesn't interact well with:
```0 { toggle_scale_mode(5); set_shift_x(0); set_shift_y(0); }```

But, tbh: good enough!  :)
