### ISSUE TITLE
montage_mode_return_proceed() and montage_mode_return_cancel() broken

### ISSUE THREAD

**Issue by magnetophon** [phillipberndt/pqiv#116]
``montage_mode_return_proceed()`` does what ``montage_mode_return_cancel()`` is supposed to do, and ``montage_mode_return_cancel()`` selects the first image in the montage.

Related: in the default bindings, there is: ``<Return>  { montage_mode_return_cancel() }``.

**Comment by phillipberndt** [comment]
Please update to the latest version, this should already have been fixed by 2.10.2!

**Comment by magnetophon** [comment]
Yes it is. Thanks!
