### ISSUE TITLE
feature request: make montage_mode_follow_proceed go to the image

### ISSUE THREAD

**Issue by magnetophon** [phillipberndt/pqiv#117]
Currently, ``montage_mode_follow_proceed`` selects an image in montage mode, but stays in montage mode.
I would like to have it go to normal mode as soon as an image is selected.
This is imho more in line with the programs that inspired the feature:  pentadactyl/vimperator/cvim/vimium/vim-easymotion.

cc @bearcatsandor @noctuid

**Comment by magnetophon** [comment]
Update: the latest release doesn't have ``montage_mode_follow_proceed``, but has that functionality under the more sensibly named ``montage_mode_follow``.
Please add back ``montage_mode_follow_proceed`` and make it actually proceed.  :)

**Comment by magnetophon** [comment]
Ah, I found the solution:
``
  g { montage_mode_follow(asdfghjkl); montage_mode_return_proceed() }
``

**Comment by phillipberndt** [comment]
`montage_mode_follow_proceed` is an internal, deliberately undocumented action I use for the implementation of follow mode (..which works by creating temporary key mappings, and there has to be an action that says "ok, follow mode is done, an image was selected.")

**Comment by magnetophon** [comment]
Well,it was in the manual in the last version...  😄
