### ISSUE TITLE
Block action chains upon `add_file` until file is loaded

### ISSUE THREAD

**Issue by phillipberndt** [phillipberndt/pqiv#119]
That will allow to do

    add_file(foo)
    goto_file_byname(foo)

without waiting, which allows awesome previews in ranger :-)

**Comment by phillipberndt** [comment]
See `action-queue` branch.

**Comment by phillipberndt** [comment]
Didn't find time to fix the remaining race conditions yet; however, this is still an improvement over what's currently in master, so I'm going to go ahead and merge this anyway.

Patch for ranger to try this -- feel free to reuse or improve and push upstream: [0001-Add-pqiv-as-an-image-previewer.diff](https://github.com/phillipberndt/pqiv/files/1992082/0001-Add-pqiv-as-an-image-previewer.txt)

**Comment by noctuid** [comment]
I had alter the patch to work with python3. I get two warnings when starting ranger (`--wait-for-images-to-appear` implies...). Doesn't it make sense to not warn about `--watch-directories` if `--actions-from-stdin` is specified? It also doesn't seem ideal that pqiv is focused when previewing the first image. I have no idea if it's possible to prevent that without doing something like using xdotool to focus the previous window. If not, it might be nice if it was possible to display the pqiv window immediately when using `--actions-from-stdin` and `--wait-for-images-to-appear` to make it easy to reselect the ranger window (e.g. user could create an alias to start ranger and then switch back to it). 

It seems a bit slow to display new images, but this is amazing. I'll definitely be using this. Having pqiv as a preview method never occurred to me. Thanks a ton.

**Comment by phillipberndt** [comment]
> Doesn't it make sense to not warn about `--watch-directories` if `--actions-from-stdin` is specified?

I warn about it to ensure that users know about this side effect. You can get rid of the warning by explicitly passing the `--watch-directories` flag as well.

> If not, it might be nice if it was possible to display the pqiv window immediately..

There's `--allow-empty-window` ("Show pqiv/do not quit even though no files are loaded"), that is, the full command line

    ./pqiv --wait-for-images-to-appear --actions-from-stdin --allow-empty-window --watch-directories --lazy-load

should work.

> It seems a bit slow to display new images, but this is amazing.

It's slower than usual because normally pqiv will preload adjacent (in pqiv's file list) images in the background for you. The speed should be comparable to navigation speed in `--low-memory` mode (which disables preloading).

**Comment by noctuid** [comment]
> You can get rid of the warning by explicitly passing the --watch-directories flag as well.

In the case of using pqiv for image preview here, `--watch-directories` doesn't actually make a difference since no directories are specified, right? It's not actually an issue, but it seems a little nonintuitive to have to specify `--watch-directories` to silence the warning.

> --allow-empty-window

Thanks, I forgot about that.

> It's slower than usual because normally pqiv will preload adjacent (in pqiv's file list) images in the background for you. The speed should be comparable to navigation speed in --low-memory mode (which disables preloading).

The neighboring files (for the current ranger sorting order) could maybe be added to get the same speed. Though maybe that wouldn't actually work well since `add_file` blocks the actions chain (and if the user wasn't going to a neighboring image, they would still have to wait for pqiv to load it before the next preview). What was the old behavior for `add_file.. goto_file_by_name`, and would it potentially make sense to have a version of `add_file` that doesn't block actions (for adding files that *might* be shown next)?

It wouldn't matter for my use case, but I wonder if it makes sense to remove images at some point to save memory.

I can potentially work on making this into a PR if you don't want to/don't have time to. I think it's pretty usable as is. Do you have any other ideas for improving it?

**Comment by phillipberndt** [comment]
> In the case of using pqiv for image preview here, `--watch-directories` doesn't actually make a difference since no directories are specified, right?

True. But I have to add `--watch-directories` when using `--wait-for-images-to-appear` because that option (if used without `--actions-from-stdin`) only makes sense with directory arguments and if pqiv is allowed to watch those directories for files to appear. If you use `--actions-from-stdin`, you almost certainly want `--wait-for-images-to-appear`. What I didn't think of is the transitive chain of dependencies - it'd make sense to remove the `--watch-directories` dependency if `--actions-from-stdin` is also given. (Or to just remove the warning.. I'll admit that it's somewhat confusing.)

> Though maybe that wouldn't actually work well since add_file blocks the actions chain (and if the user wasn't going to a neighboring image, they would still have to wait for pqiv to load it before the next preview).

It doesn't, actually. `add_file` only adds the file to the list of available images, and preloading happens in the background.

> It wouldn't matter for my use case, but I wonder if it makes sense to remove images at some point to save memory.

Only the two adjacent images are preloaded into memory at any time. If you navigate away from an image, then the images i+2/i-2 will be unloaded automatically.

**Comment by noctuid** [comment]
> Only the two adjacent images are preloaded into memory at any time. If you navigate away from an image, then the images i+2/i-2 will be unloaded automatically.

What is considered adjacent when using `--actions-from-stdin` and `add_file`? Is it the order of `add_file` calls? If only the two adjacent images are loaded at a time, and `add_file` calls won't block the next `goto_file_by_name`, I could just add all images in the current directory at once in order of ranger's sorting. That way pqiv previewing could still benefit from pqiv's preloading regardless of any jumping/navigation in ranger. If the user changed the sorting, it would remove all files and then add them in the new order. Would pqiv's current behavior allow for this to work?

**Comment by phillipberndt** [comment]
Exactly, the order of the calls - unless you're using `--sort`, then it's the other sorted by name. (I should add an option to ignore the config file..)
