### ISSUE TITLE
./.pqiv-select/

### ISSUE THREAD

**Issue by pa-d-v** [phillipberndt/pqiv#124]
By default the "a" key copies image to ./.pqiv-select/, I frequently notice that this key is pressed accidentaly since it is close to q an s (using azerty keyboard but probably the same with qwerty which has a and q switched) resulting in unwanted ./.pqiv-select folder. I had same problem with qiv before.
Is there an action nothing() we can use to disable the "a" key?
It would be great if another key further away would be bound to ./.pqiv-select by default e.g. "c" from choose/copy, I can do this already with hardlink_current_image() action I understead you try to remain compatible with qiv which uses "a" but would be nice if key further away like "c" was the default.
Thanks in advance,
Pascal

**Comment by phillipberndt** [comment]
There's nop(). And I totally see your point, that happens way too often to me, too - might make sense to rebind to e.g. ctrl+a.

**Comment by phillipberndt** [comment]
There's nop(). And I totally see your point, that happens way too often to me, too - might make sense to rebind to e.g. ctrl+a.

**Comment by phillipberndt** [comment]
There's nop(). And I totally see your point, that happens way too often to me, too - might make sense to rebind to e.g. ctrl+a.

**Comment by pa-d-v** [comment]
Thanks for the nop() hint, I agree with ctrl+a being a better default.

**Comment by pa-d-v** [comment]
Is it normal that this commit is not included into 2.10.4 release? It is showing a build failed on the commit and other commits have this too.
Thanks, Pascal

**Comment by phillipberndt** [comment]
Yes, patch releases do not contain new features or changes that alter existing behaviour. I try to roughly follow semantic versioning. 2.11 will contain this patch.
