### ISSUE TITLE
Focus of transparent window

### ISSUE THREAD

**Issue by josvanr** [phillipberndt/pqiv#125]
Hello

I'm trying a little something pqiv -c -i  -f round-corners3.png, see image below :)
So a png with full transparency in the center is displayed full screen. I set the window
to be 'always on top' using my window manager (xfwm4). The result is something 
looking like an crt monitor. 
This kind of works. All windows stay under pqiv when they hit the sides of the screen
and transparent overlay is displayed as it should. Unfortunately, if I set the window to
be 'on top', it also steals the focus from the other windows on the screen. I also 
tried qiv, that seems to work in this respect. It can handle all other windows normally
but unfortunately qiv doesnt handle transparency well. The part of the image where
there is full transparency shows the background/overlayed windows, but in areas
where there is no full transparency, it shows a blocked pattern... 

Is there a way to prevent pqiv to get the focus? I searched around for how to do this
maybe with xprop or something, but to no avail....

Jos

 
![1](https://user-images.githubusercontent.com/35400537/35922560-2c86c60e-0c1e-11e8-94f5-ceaa1c335adc.jpg)

**Comment by phillipberndt** [comment]
See https://github.com/phillipberndt/pqiv/issues/96

**Comment by josvanr** [comment]
Thnx, it worked ! I couldnt apply the patch anymore but was able to write in the lines manually. Will this patch be included in pqiv some time in the future?...

**Comment by phillipberndt** [comment]
Great! Not for the time being. If even more people ask for this I might reconsider :-) For now this use case is slightly too obscure to me..
