### ISSUE TITLE
allow pqiv to write to root x window?

### ISSUE THREAD

**Issue by bearcatsandor** [phillipberndt/pqiv#126]
Could we use pqiv to provide the wallpaper for window managers like feh can?

**Comment by phillipberndt** [comment]
There's plenty of tools doing a marvellous job for that already, and the functionality is mostly unrelated to pqiv's scope. (pqiv is an graphics file *viewer*, not a *toolbox*.) So I won't add this, sorry.

That being said, if you want to maintain a patch yourself, implementation should be pretty straightforward: For some rare situations pqiv already has code in place to render the main window into a XPixmap, see `window_prerender_background_pixmap`. All you'd have to do is to make sure that this function is always called, the background is never cleared, and to replace `window_xid` with the root window's xid (`XDefaultRootWindow(display)`).

**Comment by noctuid** [comment]
@bearcatsandor If you're not already familiar with [setroot](https://github.com/ttzhou/setroot), you might want to look at it. It's the best wallpaper setter I've tried so far.

**Comment by bearcatsandor** [comment]
@phillipberndt Understandable. Thank you.  
@noctuid Thanks for the suggestion. I'll try that one. I love the honesty in the open source community (from the readme): "This program in no way constitutes good code. I have absolutely no experience in formal programming or software development, I am merely a lowly math major."
