### ISSUE TITLE
Documentation of shortcuts

### ISSUE THREAD

**Issue by Evidlo** [phillipberndt/pqiv#127]
Liking `pqiv` so far, but I'm having a hard time finding documentation on what the shortcuts are.  The link to the manual on [your website](http://www.pberndt.com/Programme/Linux/pqiv/index.html) is broken.

It might be nice to add these shortcuts to `README.markdown` or have them show up when you hit `?`, like in the original qiv.

*edit*  I just found the `--show-bindings` option, but I think my point still stands.

**Comment by phillipberndt** [comment]
I have added a hint towards the key bindings section of the man page to the readme file, and updated the man page to include (almost) all key bindings, not just the basic ones.

Let me know if you have any further suggestions for improving the documentation!
