### ISSUE TITLE
Zoom in/out not working when tiled for large images

### ISSUE THREAD

**Issue by jgkamat** [phillipberndt/pqiv#129]
After upgrading my pqiv version (which I had frozen for unfortunately quite a while), I noticed that zoom in/out no longer worked on my system (bspwm). I also noticed that this only happens for larger images (I think large enough that pqiv has to resize them down).

I bisected, and the first commit that has the issue is 6b1f4657f8afb9e249a368a353fab1620b2c6144. 

This is a bit hard to explain, so here's a video. For each of the invocations, I'm zooming in/out with my configured keys.

Please let me know if I can provide any additional information!

https://youtu.be/NjBxz8F35sI

EDIT: `ctrl-t` solves the issue, but `alt-t` and the first three `t` cycles seem to be broken. Is there a way to enter whatever mode `ctrl-t` is bound to by default? I couldn't find a flag for it in the man page...

**Comment by phillipberndt** [comment]
Thanks for bisecting the issue!

Does it suffice to wrap

    set_scale_level_to_fit();

in the `if` with another `if(!wm_ignores_size_requests)` to fix this?

(`ctrl-t` completely disables automatic scale level computations.)

**Comment by jgkamat** [comment]
Yup, that solves the issue for me completely :)

Here's the diff of what I did (on latest master now) so there's no confusion. I'll let you apply it because I don't know enough about the code to be making changes yet

```diff
diff --git a/pqiv.c b/pqiv.c
index 13ae26a..4f6304e 100644
--- a/pqiv.c
+++ b/pqiv.c
@@ -6610,7 +6610,9 @@ gboolean window_configure_callback(GtkWidget *widget, GdkEventConfigure *event,
 		}
 
 		// Rescale the image
-		set_scale_level_to_fit();
+		if(main_window_width != event->width || main_window_height != event->height) {
+			set_scale_level_to_fit();
+		}
 		queue_draw();
 
 		// We need to redraw in old GTK versions to avoid artifacts

```

**Comment by kdienes** [comment]
I've been using pqiv from KDE / kwin in Debian Stretch using the following arguments:
./pqiv -i -t -c -P off image.png
In versions prior to this patch, the image scales as I resize the window in kwin.  After this patch, it does not.  My goal is to be able to have pqiv do the "best job possible" of showing the image given the geometry provided.  Is there still a way to do this?
