### ISSUE TITLE
Delete current image

### ISSUE THREAD

**Issue by MickeyKnox** [phillipberndt/pqiv#133]
One feature from qiv I'm missing is to delete the current image with 'd'. In the man page I found the two actions remove_file_byindex(INT) and remove_file_byname(STRING). But I did not find an action to get the index of the current image. How is that supposed to be used?

Moreover, I assume that the aformentioned actions would simply remove the file. I would prefer the file to be moved to a folder like .pqiv-trash.

So in essence, I would like there to be an action like hardlink_current_image(), but instead of copying the file to .pqiv-select, it should move the file to .pqiv-trash.

**Comment by phillipberndt** [comment]
Both actions are about removing files from the list of files known to the current pqiv session. The best way to remove files from disk is to bind a custom shell command, e.g. `-1 rm`. I don't have that in by default since I don't want users to accidentally delete stuff while they're playing around with the tool for the first time. The action to hardlink to .pqiv-select is a remnant of early qiv compatibility - ever since it's become possible to bind commands to arbitrary keys it's not really required anymore.

**Comment by Flurrywinde** [comment]
Is there a way to remove the current file from the playlist? Looking at the code, it looks like there's not, so I started writing my own. I was able to remove the current image in regular mode via the below code, but I can't figure out montage mode.
```
void remove_current() {/*{{{*/
	BOSNode *node;

	if(application_mode == DEFAULT) {
		remove_image(current_file_node);
	}
	#ifndef CONFIGURED_WITHOUT_MONTAGE_MODE
	else if(application_mode == MONTAGE) {
		if(montage_window_control.selected_node != NULL) {
			node = bostree_node_weak_unref(file_tree, montage_window_control.selected_node);
			if(node != NULL) {
				remove_image(node);
			}
		}
	}
	#endif
}/*}}}*/
```
If I call this function in montage mode, I get: `SIGSEGV (Address boundary error)`.

**Comment by neingeist** [comment]
```
pqiv-gtk3 -n --bind-key='d { command(trash $1) }' .
```

where `trash` is trash-cli, but you could also use `rm` here. I couldn't figure out how to remove the file from pqiv's playlist, too (combining commands didn't work atomic, it seemed, but I didn't try hard).

**Comment by T-3B** [comment]
For anyone coming here, this might help you, by adking the user a confirmation to delete the file from disk (`pqivrc`):
```
[keybindings]
<Delete> { command(yad --center --undecorated --skip-taskbar --on-top --title Question --image user-trash --text 'Confirm deletion' --width 200 --button Confirm:0 --button Cancel:1 && rm $1;) }
```
