### ISSUE TITLE
"set_interpolation_quality (4)" does not work

### ISSUE THREAD

**Issue by oniguri** [phillipberndt/pqiv#139]
I'm sorry for my bad English
Now I am in trouble that "set_interpolation_quality (4)" can not be set.
```
[oniguri@oniguri-pc ~]$ uname -a
Linux oniguri-pc 4.19.8-2-MANJARO #1 SMP PREEMPT Sat Dec 8 14:45:36 UTC 2018 x86_64 GNU/Linux
[oniguri@oniguri-pc ~]$ pqiv --version
pqiv 2.10.4
[oniguri@oniguri-pc ~]$ pqiv --action="set_interpolation_quality(4)" Pictures/image.jpg
Interpolation quality `4' not supported.
```
If it is a bug, please correct it.
Thank you for creating a wonderful application.

**Comment by phillipberndt** [comment]
That was indeed a bug. Thanks for letting me know! Should be fixed in latest master.
