### ISSUE TITLE
pqiv window opens in background on macos

### ISSUE THREAD

**Issue by Eyjafjallajokull** [phillipberndt/pqiv#140]
When I start pqiv it's window opens in background, behind all other windows. I've installed pqiv 2.11 via brew.

[screencast](https://gph.is/2QIqpR7)

**Comment by tonycpsu** [comment]
Seeing the same thing here as well.  MacOS 10.13.6 (17G65)

**Comment by phillipberndt** [comment]
That's a feature, sadly. Cocoa has a concept of window layering that Gtk doesn't support. See e.g. here: https://bugzilla.gnome.org/show_bug.cgi?id=782029.

I played around with fixing this in the past without success, but the workaround mentioned in the bugzilla thread looks new to me. I don't have access to a Mac anymore, so I cannot test whether it works.

I'll get back to this when I get the chance. Just don't expect anything overly soon. Or, if one of you feels up to it, I'd appreciate a PR.

**Comment by Eyjafjallajokull** [comment]
I'm on Catalina (10.15.4) and just tested @yindian change. Now pqiv window does not appear at all, executable just hangs.

I've tried `brew install --head` install and manual build.

**Comment by phillipberndt** [comment]
That's unfortunate. I'll revert the change for now. Thankls for testing this so quickly!

**Comment by l4zygreed** [comment]
@phillipberndt 
I'm learning gtk rust lib, and I found workaround, it's `Window.present()` func

in C I guess it's kinda this code
```c
gtk_window_present (GTK_WINDOW (window));
```

**Comment by phillipberndt** [comment]
Thanks! Is there any active MacOS user reading here who could verify this? It's straightforward to compile yourself with Homebrew.

**Comment by maikel** [comment]
I can try that on 10.14.6 Mojave in the evening. Would this help?

**Comment by l4zygreed** [comment]
@phillipberndt 
Ok, I'm sorry, I looked into rust library, and for macos they actually use this solution with objective-C
https://stackoverflow.com/a/47497879

I can test too, Big Sur 11.2.3 P:

**Comment by metasieben** [comment]
Since this was backed out, could the issue be reopened? 
Also, did anybody test if the new solution is working?
