### ISSUE TITLE
Print support?

### ISSUE THREAD

**Issue by sgdavis1** [phillipberndt/pqiv#153]
Has anyone ever asked for print support? `pqiv` is the first tool I have yet found that is a good replacement for the way that I use `xloadimage` (although I haven't tried that many) so I am probably adding it to all of our workstations for superfast and easy image loading (without having to fire up gimp). The only thing that I need to do through gimp now is load an image for printing :). It would be great to have an all in one package for that support.

Let me know if this is at all in the roadmap, and maybe I can convince a few of my team to help pitch in a pull request.

**Comment by phillipberndt** [comment]
Shouldn't be too hard to use a script for that. pqiv can pipe what you see into an external command. `-1"|lp -"` or something like that.

**Comment by sgdavis1** [comment]
hmm, I definitely might have to give that a try. I have to admit, I don't do a lot of command line printing...

**Comment by phillipberndt** [comment]
Gimp also has a batch mode where you can pipe Lisp into stdin - binding that to a keyboard shortcut might be an alternative if you want a UI for printing.

**Comment by sgdavis1** [comment]
I use gimp currently for any image printing needs (or evince for PDF printing). My problem is that gimp loads soooo much slower (which I am really splitting hairs here because we are talking 4 seconds versus .75 seconds for pqiv) ;) I'd love to be able to launch pqiv and hit "p" and get a cups dialog :)

**Comment by phillipberndt** [comment]
Maybe one of these tools is right for you?

https://www.linuxtopia.org/online_books/linux_system_administration/linux_printer_HOWTO/how_004.html

Basically what you're looking for is a replacement for the lp/lpr command with a gui. Then just configure that as a pipe-command in pqiv.

**Comment by sgdavis1** [comment]
Thanks for the info! I will look into the "pipe-command" in pqiv as I couldn't get it to work yesterday but I am sure I will figure it out.
