### ISSUE TITLE
Ignore images in archives

### ISSUE THREAD

**Issue by shscs911** [phillipberndt/pqiv#154]
Is it possible to ignore archives when navigating between images? I saw #70 and #94 and was thinking if it is possible to disable archive backend in the `GNUmakefile` or something like that.

**Comment by phillipberndt** [comment]
There's a command line option / configuration flag to disable backends dynamically. See `--disable-backends` in the man page.

**Comment by shscs911** [comment]
Thanks man. I was looking at the Ubuntu Bionic manpage online and it didn't have the option. On an unrelated note, `sort-key` properties should be in lowercase right?  I tried both `MTIME` and `mtime` and the latter was the one which worked.
