### ISSUE TITLE
Failed to load image out.pbm: Insufficient memory to load PNM file

### ISSUE THREAD

**Issue by nmz787** [phillipberndt/pqiv#155]
Trying to load a PBM image (1 bit depth, black and white) which is approximately 7GB and 59 GigaPixels. I've got 64GB RAM on my machine, so even if each pixel was loaded as 8 bits, it would still only be 56GB RAM thus within available resources for my machine.

**Comment by phillipberndt** [comment]
I'm afraid that might be due to actual overhead. pqiv uses RGBA internally, which blows up your image to 219 GB. I didn't really anticipate such a use-case :) I don't think this is something that can be easily fixed, the assumption that the data is RGBA is hardwired throughout the code.

**Comment by nmz787** [comment]
Ok, I'll close this ticket then. I worked around the issue with a little wxPython viewer [here](https://gist.github.com/nmz787/e442c07a897d483e2a9a0e1d99dcb709)
