### ISSUE TITLE
Force alias support

### ISSUE THREAD

**Issue by 676339784** [phillipberndt/pqiv#166]
Wondering if there is an option to disable anti-aliasing/smoothing when zooming in on an image -- much appreciated.

**Comment by phillipberndt** [comment]
You can select the interpolation mode, see the man page and https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Scaling.html#GdkInterpType for details.

**Comment by 676339784** [comment]
Thanks!
