### ISSUE TITLE
--max-depth searches an extra level deeper when file path is given

### ISSUE THREAD

**Issue by danpla** [phillipberndt/pqiv#170]
When I use `pqiv --browse --max-depth=1 PATH` when `PATH` points to a file rather than a directory, the program searches not only in the file's directory, but also in its subdirectories, as if `--max-depth` is actually 2. Similarly, `--max-depth=0` loads all files in the directory.

There's no such problem when path points to a directory.

pqiv 2.11

**Comment by phillipberndt** [comment]
Sorry for taking a bit longer :) I believe this is fixed in pqiv master. Let me know if this is still a problem for you!
