### ISSUE TITLE
endless loop in relative_image_pointer()

### ISSUE THREAD

**Issue by mmitch** [phillipberndt/pqiv#176]
I run pqiv 2.11 from Debian stable.
I use it to browse a huge image library with `pqiv --shuffle -P off --action 'toggle_scale_mode(5);' -t -i <dir1> <dir2> ...`

Sometimes the pqiv window becomes totally unresponsive. On stdout I can see a looping error message:
```
** (pqiv:496012): WARNING **: 00:15:19.958: (/build/pqiv-Jvs7gN/pqiv-2.11/pqiv.c:3111):relative_image_pointer: code should not be reached

** (pqiv:496012): WARNING **: 00:15:19.958: (/build/pqiv-Jvs7gN/pqiv-2.11/pqiv.c:3111):relative_image_pointer: code should not be reached

** (pqiv:496012): WARNING **: 00:15:19.958: (/build/pqiv-Jvs7gN/pqiv-2.11/pqiv.c:3111):relative_image_pointer: code should not be reached

** (pqiv:496012): WARNING **: 00:15:19.958: (/build/pqiv-Jvs7gN/pqiv-2.11/pqiv.c:3111):relative_image_pointer: code should not be reached
```

I don't yet know how to reproduce this bug. It might be a broken JPEG file or something related to the filesystem (it's ZFS).

I have checked the changes since version 2.11 and saw no changes related to the `relative_image_pointer()` function.
With current HEAD, the warning would be emitted at line 3124.
This is the surrounding while loop:
https://github.com/phillipberndt/pqiv/blob/e90ff7bc9738d3837493ff7294290ba2f42929c7/pqiv.c#L3117-L3128

Without a deeper understanding of the code I have a guess: Should the  `// This ought not happen :/`branch end with a `break` statement to leave the surrounding `while` loop?

**Comment by phillipberndt** [comment]
Thanks! Yes, there's a `break` missing for sure, but something else must have gone wrong, too. pqiv thinks that there's images left to add to the ordered list of images it creates for shuffled view, but when it looks for one, it can't find one.. looking at the code one way this can happen is if you attempt to move to the Nth next image, with N larger than the total number of images. I'll need to look into other things that can go wrong. Having a reproducer would be awesome..

**Comment by mmitch** [comment]
I have a minimal example to trigger the endless loop:

```sh
#!/bin/sh
subdir=test_images
mkdir -p $subdir
for number in 1 2 3 4 5 6 7; do
    convert -size 20x20 canvas:white $subdir/$number.png
done
pqiv --shuffle -i -s -d 0.01 $subdir
```

When the slideshow runs, hit `PgUp` a few times to skip to the previous image and the branch in question is entered.

**Comment by phillipberndt** [comment]
That helped a lot :) I think I fixed this bug in master. Could you please give it a try, too?

**Comment by mmitch** [comment]
Looks great, I can't make it loop any more.
Also no more warnings, so the branch really seems to be unreachable now ;-)
Thanks a lot!

**Comment by mmitch** [comment]
For the record: I've only just now used `--sort` for the first time instead of `--shuffle` and found out that `<Page_Up>` and `<Page_Down>` are bound to skip 10 files in every direction instead of just one. That propaply explains while I ran straight into this bug on my second or third invocation of _pqiv_. I was used to use these keys for navigation from my previous image viewer (_geeqie_).
