### ISSUE TITLE
Modify default window position

### ISSUE THREAD

**Issue by nikinbaidarr** [phillipberndt/pqiv#178]
How can I always open any image at a specific position in my window. I tired passing -P=`x,y' but it does not seem to work quite right?

**Comment by phillipberndt** [comment]
pqiv has a configuration file, and supports all that. Have a look at the man-page. Let me know if there's any questions left afterwards.

**Comment by nikinbaidarr** [comment]
I have a .pqivrc file with following configuration:

`--transparent-background
 --hide-info-box
`

But then if i go ahead and add

` 
--window-position=600,200
`
It will produce the following error:

`
Failed to handle non-section entry '--window-position' in configuration file.
`
Already had a decent look in the man pages. Couldn't resolve this issue.

The `--window-position` flag works perfectly if i invoke it from the terminal. But I'm looking a way to make it default.
