### ISSUE TITLE
[Feature Request] Start in montage mode if directory/multiple files are opened

### ISSUE THREAD

**Issue by nocturnalbeast** [phillipberndt/pqiv#181]
Firstly, thank you @phillipberndt for the great image viewer! Works perfectly and supports all of my image formats!

I have a feature request: is it possible to have a flag that runs the `montage_mode_enter()` action if the file(s) opened within pqiv are not a single image, rather a directory or multiple files?

If it's any help, I use a rudimentary script that tries to emulate the behavior I am trying to explain:
```
#!/usr/bin/env sh

if [ "$#" -eq 0 ]; then
    pqiv --help
elif [ "$#" -eq 1 ]; then
    if [ -f "$1" ]; then
        pqiv "$1"
    elif [ -d "$1" ]; then
        echo "montage_mode_enter()" | pqiv --actions-from-stdin "$1"
    fi
else
    echo "montage_mode_enter()" | pqiv --actions-from-stdin $@
fi
```

This works fine while running pqiv from the terminal (provided pqiv is aliased to this script), but when using something like a GUI, this might not be the case.
For example, if the directory is opened in pqiv from a file manager, then this feature could open the montage mode instead of the first file in the directory.

**Comment by phillipberndt** [comment]
I pushed a new option `--auto-montage-mode` to master. Could you check whether it's what you need?

**Comment by nocturnalbeast** [comment]
This works perfectly!

Thank you so much!
