### ISSUE TITLE
Cannot use external command to process image 

### ISSUE THREAD

**Issue by Noukkis** [phillipberndt/pqiv#182]
When using `--command-1='|convert - -blur 20 -'` (taken from the manual) or even the simpler `--command-1='|cat'` I get the following  error message when I press 1: 
`External command failed with exit status 119` 

instead of processing the image with the command and then loading the output as an image, like stated in the manual.

Same thing happen if I use `--action='command(|convert - -blur 20 -)'` or if I put it in the pqivrc.

Am I missing something here?

**Comment by phillipberndt** [comment]
Hu. This must have been broken for some time. I think I fixed it. Could you give it a try, please?

**Comment by Noukkis** [comment]
Works like a charm, thanks
