### ISSUE TITLE
easy examples of how to feed stdin from bash or python

### ISSUE THREAD

**Issue by YerCodeSmellsFunny** [phillipberndt/pqiv#187]
So I read some example code on how to use subprocess.communicate to feed pqiv via the --actions-from-stdin argument.  I was 
hoping to do something with a simple pipe and print statements though. 

(Also, I saw mention of an argument called --commands-from-stdin and also --actions-from-stdin  on the manpage.  I assume commands-from got renamed actions-from at some point and it is just vestigial documentation.  Please let me know if I am incorrect there.) 

In any case could  just a   "python pqivFeeder.py |  pqiv --actions-from-stdin *.jpg"    
work if the pqivFeeder is something simple, like 

...
    while True:
        os.system('sleep 1')
        print("""goto_file_by_index("""    +  str(index)  +      """); """)
        index += 1

(Pardon the triple quotes. I'm lazy about escaping properly.)

Thanks for any help. 
 Stay safe folks!

-Noah the Unwise

**Comment by phillipberndt** [comment]
Sure, that should work as well. You only need the power of the subprocess module when you want to react on pqiv's output (there are actions that print to stdout).

**Comment by YerCodeSmellsFunny** [comment]
Ahh actually found your 1-line example at the end of the manpage. eg

     `  echo "output_file_list(); quit()" | pqiv --actions-from-stdin test.`

Thats good enough to get people started.  I'm marking this as closed- sorry for the spam.
