### ISSUE TITLE
Feature Request: save displayed image

### ISSUE THREAD

**Issue by clemtaylor** [phillipberndt/pqiv#217]
I often use pqiv to read from stdin, where the image is comes from a camera. Today I wanted to save the image (read from the pipe) and ended up having to screen grab it to save the pixels.

I'm not sure how often people use pqiv with pipes, but sometimes it might be useful to be able to save the image. I do this all the time with mpv where it just saves the image with a filename like $HOME/mpv-shot/mpv-shot%04d.jpg. It picks the next largest frame number available.

Would this feature be useful to anyone other than me?

**Comment by phillipberndt** [comment]
You can pipe the current image to an external command by prefixing `|`. See e.g. the `-1` option. Does that cover your use case already?

**Comment by clemtaylor** [comment]
Wow, I didn't even realize this was a feature. Cool.

I ended up using:
```
command-1=|cat > $HOME/mpv-shot/pqiv-shot.$(date '+%Y%m%d.%H%M%S').png
```

pqiv complains that I don't spit back out an image for it to display, but that is harmless.
```
Failed to load image - [Output of `cat > $HOME/mpv-shot/pqiv-shot.$(date '+%Y%m%d.%H%M%S').png`]: Unrecognized image file format
```
