### ISSUE TITLE
[bug] Sorting by name does not work if input is a directory

### ISSUE THREAD

**Issue by T-3B** [phillipberndt/pqiv#224]
Simply use `pqiv --sort-key=name path/to/dir`, and unfortunately the loaded files (inside the specified directory) are not sorted when view them in `pqiv`.

This is a bit annoying when I'm reading CBZ (comic books ZIP), because most of the time inside the book there will be chapter folders and pages inside them, thus the pages won't show in order. Both chapters folder inside the comic book *and* the pages will be mixed (i.e. not sorted).

**Comment by NHOrus** [comment]
I think you need to explicitly demand sort with `pqiv -n` or sort-key does nothing.

**Comment by T-3B** [comment]
Now I feel dumb... Thanks for your help!
