### ISSUE TITLE
Segmentation Fault/Abort playing specific video file

### ISSUE THREAD

**Issue by ColdMacaroni** [phillipberndt/pqiv#247]
(As a preface, I love this program!!)

Trying to view this specific mp4 causes pqiv to segfault. I didn't do anything special to this file, I've recorded with [screencast](https://github.com/dbermond/screencast) many other times and it's worked fine. Mpv and vlc seem to play it fine. This has happened with these recordings before,, 

Video attached here: https://github.com/user-attachments/assets/77fefa63-97a0-4dd7-8e8f-d0b858ecd456

Here it is as a zip file in case github re-encodes it: [pqivsegfault.zip](https://github.com/user-attachments/files/17486661/pqivsegfault.zip)

---

Repro: Pass video file as argument. Should run into issues within less than a second.

Some of the errors:
```
~ > pqiv IMPORTANT-pqivsegfault.mp4
fish: Job 1, 'pqiv IMPORTANT-pqivsegfault.mp4' terminated by signal SIGSEGV (Address boundary error)

~ > pqiv IMPORTANT-pqivsegfault.mp4
fish: Job 1, 'pqiv IMPORTANT-pqivsegfault.mp4' terminated by signal SIGSEGV (Address boundary error)

~ > pqiv IMPORTANT-pqivsegfault.mp4
malloc(): smallbin double linked list corrupted
fish: Job 1, 'pqiv IMPORTANT-pqivsegfault.mp4' terminated by signal SIGABRT (Abort)
```

There's a small chance the video plays normally, in that case pressing `q` to exit causes the segfault/abort.

## Debug info

Coredump: [dump.tgz](https://github.com/user-attachments/files/17487136/dump.tgz)

Seems to happen in `invalidate_current_scaled_image_surface` when freeing `current_scaled_image_surface`

Backtrace (i compiled a debug libcairo 1.18.2 for better output):
```
Thread 1 "pqiv" received signal SIGSEGV, Segmentation fault.
0x00007ffff3bc55c1 in free () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff3bc55c1 in free () from /usr/lib/libc.so.6
#1  0x00007ffff3a04afc in ?? () from /usr/lib/libpixman-1.so.0
#2  0x00007ffff3a04b59 in pixman_image_unref () from /usr/lib/libpixman-1.so.0
#3  0x00007ffff7ebc91a in _cairo_image_surface_finish (abstract_surface=0x5555556a2ee0) at ../src/cairo-image-surface.c:869
#4  0x00007ffff7ef3b2d in _cairo_surface_finish (surface=surface@entry=0x5555556a2ee0) at ../src/cairo-surface.c:1043
#5  0x00007ffff7ef44e2 in cairo_surface_destroy (surface=0x5555556a2ee0) at ../src/cairo-surface.c:978
#6  0x00005555555657cc in invalidate_current_scaled_image_surface () at /home/sofa/documents/projects/programming/clones/pqiv/pqiv.c:2007
#7  0x0000555555565970 in image_animation_timeout_callback (user_data=0x555555958200) at /home/sofa/documents/projects/programming/clones/pqiv/pqiv.c:2039
#8  0x00007ffff7414ac0 in ?? () from /usr/lib/libgdk-3.so.0
#9  0x00007ffff430ea0a in ?? () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff430d559 in ?? () from /usr/lib/libglib-2.0.so.0
#11 0x00007ffff4370157 in ?? () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff430e287 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#13 0x00007ffff77e4ebf in gtk_main () from /usr/lib/libgtk-3.so.0
#14 0x0000555555577a34 in main (argc=2, argv=0x7fffffffd668) at /home/sofa/documents/projects/programming/clones/pqiv/pqiv.c:8295
(gdb) p *current_scaled_image_surface
$6 = {
  backend = 0x7ffff7fb89c0 <_cairo_image_surface_backend>,
  device = 0x0,
  type = CAIRO_SURFACE_TYPE_IMAGE,
  content = CAIRO_CONTENT_COLOR_ALPHA,
  ref_count = {
    ref_count = 0
  },
  status = CAIRO_STATUS_SUCCESS,
  unique_id = 18,
  serial = 1,
  damage = 0x0,
  _finishing = 1,
  finished = 0,
  is_clear = 0,
  has_font_options = 0,
  owns_device = 0,
  is_vector = 0,
  user_data = {
    size = 0,
    num_elements = 0,
    element_size = 24,
    elements = 0x0
  },
  mime_data = {
    size = 0,
    num_elements = 0,
    element_size = 24,
    elements = 0x0
  },
  device_transform = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = 0,
    y0 = 0
  },
  device_transform_inverse = {
    xx = 1,
    yx = 0,
    xy = 0,
    yy = 1,
    x0 = 0,
    y0 = 0
  },
  device_transform_observers = {
    next = 0x5555556a2fa8,
    prev = 0x5555556a2fa8
  },
  x_resolution = 72,
  y_resolution = 72,
  x_fallback_resolution = 300,
  y_fallback_resolution = 300,
  snapshot_of = 0x0,
  snapshot_detach = 0x0,
  snapshots = {
    next = 0x5555556a2fe8,
    prev = 0x5555556a2fe8
  },
  snapshot = {
    next = 0x0,
    prev = 0x0
  },
  font_options = {
    antialias = CAIRO_ANTIALIAS_DEFAULT,
    subpixel_order = CAIRO_SUBPIXEL_ORDER_DEFAULT,
    lcd_filter = CAIRO_LCD_FILTER_DEFAULT,
    hint_style = CAIRO_HINT_STYLE_DEFAULT,
    hint_metrics = CAIRO_HINT_METRICS_DEFAULT,
    round_glyph_positions = CAIRO_ROUND_GLYPH_POS_DEFAULT,
    variations = 0x0,
    color_mode = CAIRO_COLOR_MODE_DEFAULT,
    palette_index = 0,
    custom_palette = 0x0,
    custom_palette_size = 0
  },
  foreground_source = 0x0,
  foreground_used = 0
}
```

## Other Info
pqiv version: pqiv 2.13.1-3-gb251f01(built from latest master commit as of writing)
OS: arch linux
<details><summary>ldd output</summary>
<pre>
        linux-vdso.so.1 (0x00007a237db9f000)
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007a237d200000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007a237d9e6000)
        libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007a237d9d6000)
        libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007a237d1da000)
        libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x00007a237d9cd000)
        libgdk-3.so.0 => /usr/lib/libgdk-3.so.0 (0x00007a237d0ed000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007a237d0d4000)
        libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007a237d06b000)
        libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007a237ce9c000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007a237cd5b000)
        libarchive.so.13 => /usr/lib/libarchive.so.13 (0x00007a237cc86000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007a237cc41000)
        libavformat.so.61 => /usr/lib/libavformat.so.61 (0x00007a237c800000)
        libavcodec.so.61 => /usr/lib/libavcodec.so.61 (0x00007a237b200000)
        libswscale.so.8 => /usr/lib/libswscale.so.8 (0x00007a237cba6000)
        libavutil.so.59 => /usr/lib/libavutil.so.59 (0x00007a237a000000)
        libpoppler-glib.so.8 => /usr/lib/libpoppler-glib.so.8 (0x00007a237cb2e000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007a2379eb0000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007a237cace000)
        libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007a2379d79000)
        libspectre.so.1 => /usr/lib/libspectre.so.1 (0x00007a237cab6000)
        libMagickWand-7.Q16HDRI.so.10 => /usr/lib/libMagickWand-7.Q16HDRI.so.10 (0x00007a2379c2f000)
        libMagickCore-7.Q16HDRI.so.10 => /usr/lib/libMagickCore-7.Q16HDRI.so.10 (0x00007a2379800000)
        libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007a237c78e000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007a2379b40000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007a237960f000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007a237d9be000)
        libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007a237c772000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007a237c722000)
        libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007a237c702000)
        libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x00007a2379502000)
        libXi.so.6 => /usr/lib/libXi.so.6 (0x00007a237c6ef000)
        libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x00007a237b1c6000)
        libcloudproviders.so.0 => /usr/lib/libcloudproviders.so.0 (0x00007a237c6d6000)
        libtinysparql-3.0.so.0 => /usr/lib/libtinysparql-3.0.so.0 (0x00007a2379430000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007a237b1be000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007a2379366000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007a237b19c000)
        libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007a237b154000)
        libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007a237b145000)
        libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007a237b13b000)
        libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007a237b136000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007a2379b2b000)
        libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007a237935a000)
        libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007a237b131000)
        libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007a2379355000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007a2379348000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007a2379343000)
        libthai.so.0 => /usr/lib/libthai.so.0 (0x00007a2379338000)
        libmount.so.1 => /usr/lib/libmount.so.1 (0x00007a23792e9000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007a23792be000)
        libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007a2378c00000)
        libacl.so.1 => /usr/lib/libacl.so.1 (0x00007a23792b5000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007a2379282000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007a23791a3000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007a237917e000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007a237916b000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007a2378ab3000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007a2379130000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007a2378a15000)
        libtiff.so.6 => /usr/lib/libtiff.so.6 (0x00007a2378988000)
        libdvdnav.so.4 => /usr/lib/libdvdnav.so.4 (0x00007a2379119000)
        libdvdread.so.8 => /usr/lib/libdvdread.so.8 (0x00007a23790f8000)
        libmodplug.so.1 => /usr/lib/libmodplug.so.1 (0x00007a23787fa000)
        libopenmpt.so.0 => /usr/lib/libopenmpt.so.0 (0x00007a237860a000)
        libvapoursynth-script.so.0 => /usr/lib/libvapoursynth-script.so.0 (0x00007a23790f1000)
        libbluray.so.2 => /usr/lib/libbluray.so.2 (0x00007a23785ad000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007a2378507000)
        libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007a237830b000)
        libsrt.so.1.5 => /usr/lib/libsrt.so.1.5 (0x00007a2378232000)
        libssh.so.4 => /usr/lib/libssh.so.4 (0x00007a23781bb000)
        libzmq.so.5 => /usr/lib/libzmq.so.5 (0x00007a23780d6000)
        libswresample.so.5 => /usr/lib/libswresample.so.5 (0x00007a23780b7000)
        libvpx.so.9 => /usr/lib/libvpx.so.9 (0x00007a2377c00000)
        libwebpmux.so.3 => /usr/lib/libwebpmux.so.3 (0x00007a23790e3000)
        libdav1d.so.7 => /usr/lib/libdav1d.so.7 (0x00007a2377a21000)
        libopencore-amrwb.so.0 => /usr/lib/libopencore-amrwb.so.0 (0x00007a23780a1000)
        librsvg-2.so.2 => /usr/lib/librsvg-2.so.2 (0x00007a2377400000)
        libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x00007a23790d2000)
        libaom.so.3 => /usr/lib/libaom.so.3 (0x00007a2376a00000)
        libgsm.so.1 => /usr/lib/libgsm.so.1 (0x00007a2378092000)
        libjxl.so.0.11 => /usr/lib/libjxl.so.0.11 (0x00007a2376600000)
        libjxl_threads.so.0.11 => /usr/lib/libjxl_threads.so.0.11 (0x00007a237808a000)
        libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007a2378013000)
        libopencore-amrnb.so.0 => /usr/lib/libopencore-amrnb.so.0 (0x00007a2377fe9000)
        libopenjp2.so.7 => /usr/lib/libopenjp2.so.7 (0x00007a2377f84000)
        libopus.so.0 => /usr/lib/libopus.so.0 (0x00007a2376000000)
        librav1e.so.0.7 => /usr/lib/librav1e.so.0.7 (0x00007a2375c00000)
        libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007a2377f66000)
        libSvtAv1Enc.so.2 => /usr/lib/libSvtAv1Enc.so.2 (0x00007a236d400000)
        libtheoraenc.so.1 => /usr/lib/libtheoraenc.so.1 (0x00007a2377f2e000)
        libtheoradec.so.1 => /usr/lib/libtheoradec.so.1 (0x00007a2377a07000)
        libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007a23779d9000)
        libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007a237792e000)
        libx264.so.164 => /usr/lib/libx264.so.164 (0x00007a236d000000)
        libx265.so.209 => /usr/lib/libx265.so.209 (0x00007a236bc00000)
        libxvidcore.so.4 => /usr/lib/libxvidcore.so.4 (0x00007a23772f3000)
        libva.so.2 => /usr/lib/libva.so.2 (0x00007a23778f8000)
        libvpl.so.2 => /usr/lib/libvpl.so.2 (0x00007a2377297000)
        libva-drm.so.2 => /usr/lib/libva-drm.so.2 (0x00007a2377f25000)
        libva-x11.so.2 => /usr/lib/libva-x11.so.2 (0x00007a2377f1e000)
        libvdpau.so.1 => /usr/lib/libvdpau.so.1 (0x00007a23778f3000)
        libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007a2377280000)
        libOpenCL.so.1 => /usr/lib/libOpenCL.so.1 (0x00007a23769d6000)
        libpoppler.so.141 => /usr/lib/libpoppler.so.141 (0x00007a236b800000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007a236b400000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007a23769a8000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007a237dba1000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007a2376909000)
        libffi.so.8 => /usr/lib/libffi.so.8 (0x00007a23778e8000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007a2377274000)
        libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007a23768fa000)
        libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007a23778e1000)
        libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007a2376556000)
        libgs.so.10 => /usr/lib/libgs.so.10 (0x00007a2369e00000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007a2375fad000)
        liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x00007a2375f45000)
        libraqm.so.0 => /usr/lib/libraqm.so.0 (0x00007a23768f1000)
        liblqr-1.so.0 => /usr/lib/liblqr-1.so.0 (0x00007a23768e2000)
        libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x00007a2369a00000)
        libltdl.so.7 => /usr/lib/libltdl.so.7 (0x00007a23768d7000)
        libsharpyuv.so.0 => /usr/lib/libsharpyuv.so.0 (0x00007a23768ce000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007a237652c000)
        libatspi.so.0 => /usr/lib/libatspi.so.0 (0x00007a2375bc9000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007a2375b78000)
        libjson-glib-1.0.so.0 => /usr/lib/libjson-glib-1.0.so.0 (0x00007a2375b4e000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007a236b694000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007a2375f36000)
        libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007a23768c5000)
        libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007a2375b15000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007a2376527000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007a2375f2e000)
        libicuuc.so.75 => /usr/lib/libicuuc.so.75 (0x00007a2369806000)
        libjbig.so.2.1 => /usr/lib/libjbig.so.2.1 (0x00007a2375f20000)
        libmpg123.so.0 => /usr/lib/libmpg123.so.0 (0x00007a2375ab9000)
        libvorbisfile.so.3 => /usr/lib/libvorbisfile.so.3 (0x00007a2375aae000)
        libpython3.12.so.1.0 => /usr/lib/libpython3.12.so.1.0 (0x00007a2369000000)
        libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007a2369c9d000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007a2375a8c000)
        libunistring.so.5 => /usr/lib/libunistring.so.5 (0x00007a2369656000)
        libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007a2375a77000)
        libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007a236d3b7000)
        libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007a236d360000)
        libsodium.so.26 => /usr/lib/libsodium.so.26 (0x00007a236d301000)
        libpgm-5.3.so.0 => /usr/lib/libpgm-5.3.so.0 (0x00007a236cfb6000)
        libsoxr.so.0 => /usr/lib/libsoxr.so.0 (0x00007a236cf55000)
        libjxl_cms.so.0.11 => /usr/lib/libjxl_cms.so.0.11 (0x00007a236d2ca000)
        libhwy.so.1 => /usr/lib/libhwy.so.1 (0x00007a2375a6b000)
        libbrotlienc.so.1 => /usr/lib/libbrotlienc.so.1 (0x00007a2368f4e000)
        libogg.so.0 => /usr/lib/libogg.so.0 (0x00007a2375a61000)
        libmvec.so.1 => /usr/lib/libmvec.so.1 (0x00007a2368e56000)
        libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007a2375a5c000)
        libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007a2375a55000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007a2368d87000)
        libgpgmepp.so.6 => /usr/lib/libgpgmepp.so.6 (0x00007a236bb9b000)
        libsmime3.so => /usr/lib/libsmime3.so (0x00007a236cf2a000)
        libnss3.so => /usr/lib/libnss3.so (0x00007a2368c4e000)
        libplc4.so => /usr/lib/libplc4.so (0x00007a2375a4e000)
        libnspr4.so => /usr/lib/libnspr4.so (0x00007a236b3c1000)
        libXt.so.6 => /usr/lib/libXt.so.6 (0x00007a2369c37000)
        libcups.so.2 => /usr/lib/libcups.so.2 (0x00007a2368bbf000)
        libijs-0.35.so => /usr/lib/libijs-0.35.so (0x00007a236cf22000)
        libjbig2dec.so.0 => /usr/lib/libjbig2dec.so.0 (0x00007a236cf02000)
        libidn.so.12 => /usr/lib/libidn.so.12 (0x00007a2368b8a000)
        libpaper.so.2 => /usr/lib/libpaper.so.2 (0x00007a236cefd000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007a2368a96000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007a2369633000)
        libicudata.so.75 => /usr/lib/libicudata.so.75 (0x00007a2366c00000)
        libnghttp3.so.9 => /usr/lib/libnghttp3.so.9 (0x00007a2368a73000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007a2368a49000)
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007a2368a00000)
        libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007a236bb87000)
        libssl.so.3 => /usr/lib/libssl.so.3 (0x00007a2366b25000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007a23689ad000)
        libgpgme.so.11 => /usr/lib/libgpgme.so.11 (0x00007a236895e000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0x00007a2366af8000)
        libplds4.so => /usr/lib/libplds4.so (0x00007a236cef8000)
        libSM.so.6 => /usr/lib/libSM.so.6 (0x00007a236b68a000)
        libICE.so.6 => /usr/lib/libICE.so.6 (0x00007a2366adc000)
        libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x00007a2366ace000)
        libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x00007a2366abc000)
        libcap.so.2 => /usr/lib/libcap.so.2 (0x00007a2368952000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007a23669f7000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007a23669ca000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007a236bb81000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007a23669bc000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007a236b3ba000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007a23669aa000)
        libassuan.so.9 => /usr/lib/libassuan.so.9 (0x00007a2366995000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007a236696d000)
        libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007a2369c2d000)
</pre>
</details>

**Comment by phillipberndt** [comment]
Thanks for the detailed report! This patch helps for me, does it fix the issue for you, too?

```
diff --git a/backends/libav.c b/backends/libav.c
index e339e3d..f3bfee7 100644
--- a/backends/libav.c
+++ b/backends/libav.c
@@ -295,7 +295,7 @@ void file_type_libav_load(file_t *file, GInputStream *data, GError **error_point
 #if LIBAVUTIL_VERSION_INT < AV_VERSION_INT(55, 0, 0)
        size_t num_bytes = avpicture_get_size(PIX_FMT_RGB32, file->width, file->height);
 #else
-       size_t num_bytes = av_image_get_buffer_size(AV_PIX_FMT_RGB32, file->width, file->height, 16);
+       size_t num_bytes = av_image_get_buffer_size(AV_PIX_FMT_RGB32, file->width, file->height, 64);
 #endif
        private->buffer = (uint8_t *)g_malloc(num_bytes * sizeof(uint8_t));
 
```

(I found this by trial and error. This looks like some of the software scaling in ffmpeg has been optimized to use vector instructions; I haven't bothered checking which, yet.)

**Comment by ColdMacaroni** [comment]
Oh yes that fixes it! That's interesting,,

I tried it with a bunch of other videos as well and they all worked fine. Thanks!!

**Comment by phillipberndt** [comment]
Great, I'll merge that change soon then.

I suspect that most videos will have a resolution that naturally leads to the required alignment.
