### ISSUE TITLE
toggle shuffle mode

### ISSUE THREAD

**Issue by SpaceCadet2000** [phillipberndt/pqiv#30]
I was wondering if it would be possible to add a hotkey that allows you to toggle the shuffle mode on and off while you are viewing images.

The way I imagine it would work is as follows: 
* User starts pqiv with the --shuffle option to flip randomly through a large collection of images
* User sees something he likes, and wants to see the next or previous image in the set rather than the next random image
* User presses the hotkey "R" (for random) to toggle shuffle mode off, so that he can view the images that are alphabetically adjacent to the one he was viewing.

**Comment by phillipberndt** [comment]
Merged. The current binary (see readme) already includes these changes.
