### ISSUE TITLE
scale-images-up in .pqivrc causes SEGV

### ISSUE THREAD

**Issue by tomdenny** [phillipberndt/pqiv#33]
If the `scale-images-up=1` is in .pqivrc, it causes a SEGV fault in pqiv on my raspberry pi.  I believe this is likely to happen with any option that uses the underlying CALLBACK framework in the code.

The fix for me was simple (two changes on line 590 in the current pqiv.c code)
```c
 (*(GOptionArgFunc)(iter->arg_data))(iter->long_name, option_value, NULL, &error_pointer);
/* INSTEAD OF
** (*(GOptionArgFunc *)(iter->arg_data))(NULL, option_value, NULL, &error_pointer);
*/
```

Thanks for creating this utility.  It's working well for what I needed it for.

**Comment by phillipberndt** [comment]
Thanks! With your fix, while the segfault is gone, you still shouldn't get the desired behaviour. "--" must be prepended to long_name for the callback to properly recognize the option.
