### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by imShara** [phillipberndt/pqiv#34]
Can `--browse` be sorted by file creation time?

**Comment by phillipberndt** [comment]
https://github.com/phillipberndt/pqiv/tree/sort-by-time is a simple solution for this.

**Comment by imShara** [comment]
Thanks, this feature need to be in master

**Comment by phillipberndt** [comment]
It'll be. But I might do some changes before: While prepending the sort key to the displayed file name (which is used for sorting) is a very simple solution, I'm not really content with also displaying it in the info box. Also, it might be useful to rename the option to something like `--sort-order=mtime` for forward compatibility.

**Comment by phillipberndt** [comment]
I ended up naming the option `--sort-key=mtime`, but I implemented this now. I'll test this myself for some days and then pull the change to master!

**Comment by imShara** [comment]
Brilliant!

**Comment by phillipberndt** [comment]
Merged to master.

**Comment by imShara** [comment]
Doesn't work with `--browse`, e.g
```bash
pqiv --browse --sort-key=mtime ./image.png
```

**Comment by phillipberndt** [comment]
Works fine here. If you're referring to `image.png` being displayed first, then that's intentional. The files are sorted by mtime, but pqiv starts at the position of the image that was given as a parameter. If the order is wrong entirely, then could you provide an example, please? (The output of `ls -lt --time-style="+[%s] (%Y-%m-%d %H:%M:%S)"` + the actual order in pqiv should suffice.)

**Comment by imShara** [comment]
```bash
ls -lt --time-style="+[%s] (%Y-%m-%d %H:%M:%S)"

-rw-r--r-- 1 shara shara 3041 [1441832654] (2015-09-10 00:04:14) fourth.png
-rw-r--r-- 1 shara shara 5430 [1441832570] (2015-09-10 00:02:50) third.png
-rw-r--r-- 1 shara shara 4793 [1441832530] (2015-09-10 00:02:10) second.png
-rw-r--r-- 1 shara shara 1802 [1441832216] (2015-09-09 23:56:56) first.png

pqiv --browse --sort-key=mtime ./first.png
```

Showed as:
[1/4] first
[2/4] third
[3/4] second
[4/4] fourth

```bash
pqiv --browse --sort-key=mtime ./second.png
```

Showed as:
[1/4] second
[2/4] first
[3/4] third
[4/4] fourth

**Comment by phillipberndt** [comment]
Here, I see them in order first, second, third, fourth and second, third, fourth, first, respectively.

Which GTK/glib versions, OS, and filesystem do you use?

**Comment by phillipberndt** [comment]
Ah. I guess I know what the problem might be: You do not have a configuration file that actually *enables* sorting, right? Try adding `--sort` to your command line.

**Comment by imShara** [comment]
Yep, with `--sort` key works perfect, thank you!
