### ISSUE TITLE
Webm support

### ISSUE THREAD

**Issue by hetraeus** [phillipberndt/pqiv#37]
Pretty much no linux image viewer supports it and I do not feel comfortable with a media player. May this happen eventually?

**Comment by onodera-punpun** [comment]
That's probably because webm is a video format

**Comment by hetraeus** [comment]
FYI soundless WEBM is replacing GIFs here and there in the web. It is becoming pretty common.

**Comment by phillipberndt** [comment]
I thought about generic video support a while ago, but then did not implement it because I could not find any real use case. Yours sounds good enough for me to give it a try.  

See the libav branch for an early and experimental version of the new backend.

**Comment by onodera-punpun** [comment]
Does it use libav as in the fork of ffmpeg libav? If so: Why? All the distros that used to use libav are switching back to ffmpeg (ubuntu, debian), and the rest already uses ffmpeg.

**Comment by phillipberndt** [comment]
I've tested the backend with both the libav fork and the latest ffmpeg release now. While everything works *somehow*, it appears that frames should be read continuously from a separate thread and queued instead of the read-as-needed basis I'm currently using – I'm experiencing load-dependent glitches/frame drops/fragment errors, but only with larger videos. Small animations seem to run fine mostly. Please test this feature, I'm eager for feedback 😉

I'm tempted to leave it in its current state and ship it flagged such that it is not compiled in unless explicitly selected in `configure` (I share @onodera-punpun's opinion that video support is an uncommon feature for image viewers..).

**Comment by hetraeus** [comment]
I just tested it. It runs seamlessly between image, gifs, and webm! Excellent!

I did a PKGBUILD, so Arch Linux testers may help theirselves
https://aur.archlinux.org/packages/pqiv-git/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pqiv-git

Wokrs for me. Should I close this ticket?

**Comment by phillipberndt** [comment]
Great! I'll close it once I merge this, with which I'm going to wait until I've had a chance to test this further & on different platforms.

**Comment by phillipberndt** [comment]
I've tested this in Ubuntu with both the libav fork and the latest ffmpeg, on FreeBSD and on Windows using mxe now. Seems to work smoothly everywhere. I merged the code to master now.

The only thing that might turn out to be a problem could be the reading-fames-as-needed thing. We'll see about that.

**Comment by onodera-punpun** [comment]
I tried compiling this with the lates ffmpeg (2.8, I also tried 2.7.4) but I keep getting the following:

```
/usr/bin/ld: backends/libav.o: undefined reference to symbol 'av_frame_alloc@@LIBAVUTIL_54'
/usr/lib/libavutil.so.54: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
GNUmakefile:115: recipe for target 'pqiv' failed
```

**Comment by RaitaroH** [comment]
@phillipberndt I am a bit confused regarding webm support. I have version 2.11 and according to the changelog this should support webm, right? Testing it with [this file from wikipedia](https://en.wikipedia.org/wiki/File:Schlossbergbahn.webm) pqiv gives:
```
$ pqiv Schlossbergbahn.webm
Didn't recognize file `Schlossbergbahn.webm': Both its extension and MIME-type `video/webm' are unknown. Fall-back to default file handler.
Failed to load image Schlossbergbahn.webm: Unrecognized image file format
No images left to display.
```
I have installed the package from AUR, so 2.11-3 and `libwebp` is a dependency for it, I am not missing it. Also, the git version for the AUR package in the readme is dead.
