### ISSUE TITLE
Feature request, --once option

### ISSUE THREAD

**Issue by TommyFlowers** [phillipberndt/pqiv#38]
Would it be possible to add a new option, say, --once that would mean pqiv starts in slideshow mode, displays all pictures available just once and then exits? In other words, it does not wrap around.

Probably this new option would be ignored if --shuffle was supplied?

Many thanks for consideration.

**Comment by phillipberndt** [comment]
Have a look at the *feature-disable-wrap* branch. It's not exactly what you want, but should be close: It adds an option `--disable-wrap-around` to make pqiv stop in slideshow mode once the last image has been reached. If `--watch-directories` is set and a new image is found, pqiv then continues the slideshow. (It does not work with `--shuffle` yet, but it should not be a problem to extend the feature such that pqiv begins to wait once all images have been seen once.)

Would this suffice, or do you need pqiv to exit once every image has been seen?

**Comment by TommyFlowers** [comment]
It's very close but not quite!

I have a use case to show images randomly but then display any new images that have arrived in a certain time period. I do this by starting a second, temporary, pqiv instance on just the new arrived images. The first instance uses --shuffle and --watch-directories. Ideally the second instance would run  through its slideshow and exit, leaving the first instance to pick up the new images as normal.

**Comment by phillipberndt** [comment]
Normal shuffle mode remembers which pictures were already viewed and selects the next image randomly from all images that have not. Only once all images have been viewed, the list is emptied and a new cycle begins. New images count as not already viewed. i.e. if you start up pqiv with `--shuffle` and `--watch-directories`, you can be certain that new images are displayed before the cycle repeats. 

Does this chance anything? If it does not, I'll add something like `--once`.

**Comment by TommyFlowers** [comment]
Thanks for the info. I ran a test to try a achieve the above behaviour. It looks close but not quite.

I start with 6 images in a folder and start pqiv with:

pqiv -s -f -F -d 5.0 --watch-directories --shuffle ~/photos

The info box shows images loading in the following order:

4/6
5/6
3/6
6/6
1/6
5/6 <- image 2 seems to have been forgotten?
3/6
4/6
1/6
4/6
2/6 <- First time image 2 is displayed
5/6
3/6

I then copy 2 new images into the ~/photos folder. The sequence continues as follows:

3/8
1/8
2/8
8/8 <- First new image displayed
3/8
4/8
7/8 <- Second new image


Some observations:
1. pqiv picks up the new images - info box starts showing image x/8. This is good.
2. However, it doesn't display the first new image until a few old ones have gone by. Ideally (for my use case at least) once pqiv spots new images it starts displaying only those
3. After the 1st new image is displayed a few old images are displayed before the final new one is shown. Could this be the same as the issue above where image 2 was forgotten?

Thanks again for your help.

**Comment by phillipberndt** [comment]
This is indeed a bug, thanks for spotting it! I'll fix it asap.

> However, it doesn't display the first new image until a few old ones have gone by. Ideally (for my
> use case at least) once pqiv spots new images it starts displaying only those

Then a bugfix won't resolve this issue for you, since the next image after adding new ones will be selected from all images that have not been viewed yet in the current cycle, plus the new ones, and not only from the new ones. I don't think that this requirement is sufficiently common to add it to the shuffle mode. → I'll simply add `--once`, but probably name it `--end-of-slideshow-action=quit` or similar.

**Comment by TommyFlowers** [comment]
No problem at all!
Potentially an option like "--prefer-new-images" implemented as a separate list containing the new images that pqiv dips into first if this option is supplied would be the absolute ideal!

But certainly, the new option will be completely fine for our case for now - so many thanks again.

**Comment by phillipberndt** [comment]
For the first half of this, see 5099201a8ab5b2ca3076c830c0287eecf99b5d92.

**Comment by phillipberndt** [comment]
..and 981d2387592c227a7eb6b0c6c87d002a5caf85d4 in the [feature-end-of-slideshow-action branch](https://github.com/phillipberndt/pqiv/tree/feature-end-of-slideshow-action) for the other one. `--end-of-files-action=quit` should work, please give it a try.

**Comment by TommyFlowers** [comment]
Tested 5099201. Works great - thanks.

Will test out the feature branch soon.

**Comment by TommyFlowers** [comment]
I've tested the feature branch. Works perfectly. Many thanks for this.

Will you merging to master?

**Comment by phillipberndt** [comment]
Great. Just did. 😊
