### ISSUE TITLE
feature request: show brand/logo every n images

### ISSUE THREAD

**Issue by manu09** [phillipberndt/pqiv#39]
I would like to show a logo every 10 images. I know I can put in the logo image file after 10 images again and again, but this wouldn't work with shuffle option.

**Comment by phillipberndt** [comment]
While I see the application, this seems a bit too uncommon a feature to add. Sorry. Here's some options, let me know if I can be of assistance with any of them:

* Do not use pqiv's shuffle mode. Instead, use `--additional-from-stdin`, the coreutils tool `shuf` and a bash script. If you need reshuffling after the slideshow has completed, have a look at the new `--end-of-files-action=quit` option
* Use normal slideshow/shuffle mode and a script to start a second pqiv instance with the logo every `<slideshow interval> * 10` seconds, and kill it after some seconds
* A feature that apparently would be handy would be to be able to control pqiv from stdin; with such a feature, you could let a bash script control pqiv and jump to the logo every n seconds. (At this point, this is only a feature I'm considering, not something you can already do.)

**Comment by phillipberndt** [comment]
> A feature that apparently would be handy would be to be able to control pqiv from stdin; with such a feature, you could let a bash script control pqiv and jump to the logo every n seconds. (At this point, this is only a feature I'm considering, not something you can already do.)

FYI: If you're still interested in this, have a look at the `actions` branch and the `--commands-from-stdin` option (see `--show-keybindings` for available commands). I'm open for suggestions for commands that are missing -- your use case would certainly benefit from an option to jump to a specific file, I already have that one on my list.

**Comment by phillipberndt** [comment]
This is now possible in the latest master version.

**Comment by manu09** [comment]
Oh sorry, didn't use pqiv in a while. Omg thank you sir! :kissing_cat: :heart:
