### ISSUE TITLE
`--end-of-slideshow-action=quit` does not work if there only is one file

### ISSUE THREAD

**Issue by phillipberndt** [phillipberndt/pqiv#40]
See title. This prevents cool stuff like `pqiv --slideshow --end-of-files-action=quit --slideshow-interval=10 foo.png` (show foo.png for 10 seconds then quit).

**Comment by TommyFlowers** [comment]
I just spotted that also!

**Comment by phillipberndt** [comment]
A fix is now committed. As a workaround for earlier versions, adding `--shuffle` to the above command line also mitigates the bug.
