### ISSUE TITLE
Feature request: Scale image up when scaling window up.

### ISSUE THREAD

**Issue by onodera-punpun** [phillipberndt/pqiv#45]
It currently scales the image down when you scale the window down, however when you scale the window up the image doesn't, instead it adds a black background/border: https://sr.ht/3BDQ.png

**Comment by phillipberndt** [comment]
That behaviour is a compromise because there are (e.g. tiling) window managers that do not support windows with arbitrary sizes. If you use `--scale-images-up`, then images will always fill the window. It would be an option to make this configurable though.

**Comment by onodera-punpun** [comment]
Oh I didn't know about `--scale-images-up`, thanks, it's exactly what I wanted!

**Comment by phillipberndt** [comment]
Mind that the option has the side effect that images will be resized to fill 80% of the screen. (By default, pqiv resizes such that the image is shown at 100% zoom, unless it is to big.)
