### ISSUE TITLE
Memory leak on PNG files

### ISSUE THREAD

**Issue by imShara** [phillipberndt/pqiv#46]
Look, here is example of bug. Pqiv can't open file, but it's process gets all RAM.
![m1_20150520_124716](https://cloud.githubusercontent.com/assets/4913196/10420830/e1abf4b8-70a4-11e5-84dc-5384db2204f3.png)

```
top
873,2m 269,1m  43,0  4,6   0:54.70 R pqiv
```

Image's not broken, it's SSTV dump made with QSSTV

**Comment by phillipberndt** [comment]
Either Girhub altered the image whilst uploading, or I cannot reproduce the bug here?!

**Comment by imShara** [comment]
Hm, wait, you are right, it's working now. I will create problem-receipt later.

**Comment by imShara** [comment]
I'm sorry, i found the trouble. It's loads files recursive with --browse key and without --max-depth limit. And I have limit in command line associated with jpeg files, but not with png files. It's a mess, pqiv woks perfect.
