### ISSUE TITLE
Some Suggestions for User-set Key Bindings

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#47]
First of all, thank you for the nice image viewer. I've tried countless ones in the past, and this one is probably my favorite so far.

I think that having named actions instead of aliasing keys to other keys would be more readable. This would be especially nice for allowing for an arbitrary number of shell commands to be bound to any key (instead of using something like `command-1=...` with `keyboard-alias=a1`). It might also be nice to allow binding a key to change a specific option's value (e.g. set slideshow-interval to 0.5). To improve readability further, I think it would be nice to allow for multiple `keyboard-alias` options to be specified. I've changed a lot of the key bindings in the config file, and the rebinds I've made are not at all obvious from looking at a bunch of characters. Also, I'm not sure how to rebind keys like control-\<key\> or space (or if it's possible).

Another feature that would be great is support sequence key bindings. As a simple example, `zi` could be bound to zoom in, and `zo` could be bound to zoom in. If this ends up being implemented, I think it would be preferable to wait for the end of a chain or for an unbound key press instead of timing out. For example, if `z`, `zi`, and `zo` were bound, pressing `z` would wait for the next key press (as opposed to eventually timing out to the action bound to `z`). If `i` or `o` was pressed after the `z`, the bound actions would happen. If a key unbound at that level was pressed, it would reset to the "top level" key bindings.

Some of these requests would require changing the keybinding syntax. If you like any of the ideas, I'd recommend something similar to the following:
```
bind-key=<key> <action>
# single key
bind-key=a slideshow-toggle
# key sequence
bind-key=zi zoom-in
# control + f
bind-key=c-f fullscreen-toggle
# special characters
bind-key=<space> next-image
# g followed by space followed by control + f
bind-key=g<space>c-f shell-command ...
```

Finally, I think it would be nice to be able to unbind a key (bind to no action)

**Comment by phillipberndt** [comment]
Progress report: The `actions` branch contains everything that is needed for this now, it only has some rough edges left & lacks some features (the obvious ones now possible: reading commands from stdin, binding stuff that isn't possible at all right now, like "jump to the image called foobar.png", ..)

`pqiv --show-keybindings` outputs the current key bindings. Here's an excerpt to show the syntax:

```
                    <Mouse-1>  { move_file(-1) } 
         <Control><BackSpace>  { move_directory(-1) } 
                <KP_Subtract>  { set_scale_level_relative(0.9) } 
                            1  { numeric_command(1) } 
             <Control><minus>  { set_slideshow_interval_relative(-1) } 
            <Control><KP_Add>  { set_slideshow_interval_relative(1) } 
       <Control><KP_Subtract>  { set_slideshow_interval_relative(-1) } 
                       <Left>  { shift_x(10) } 
                         <Up>  { shift_y(10) } 
                      <Right>  { shift_x(-10) } 
```

`pqiv --bind-key="..."` can be used to set/alter key bindings. (Especially, `pqiv --bind-key="$(pqiv --show-keybindings)"` works)

A neat way to do this from the configuration file is still missing, that's next on my list.

**Comment by phillipberndt** [comment]
> A neat way to do this from the configuration file is still missing, that's next on my list.

Done, see the `configurable-features` branch, closing this, will merge soon.

**Comment by noctuid** [comment]
Awesome, thanks! I look forward to it being merged.

**Comment by imShara** [comment]
Terrible non-intuitive syntax. How to rewrite this deprecated shell action?
`pqiv -1 'echo -n $1 | xclip -filter -selection clipboard' --keyboard-alias=c1 "$1"`

**Comment by phillipberndt** [comment]
I've got to admit that it has become more complex, but that necessarily happens when a system becomes more powerful.. the equivalent of your command line is

    pqiv --bind-key="c { command(echo -n $1 | xclip -filter -selection clipboard) }"

Now that you know the new syntax, do you still consider this too complicated? I could

* revive `--keyboard-alias` (with little overhead) in the new system
* add an example to the manual page
* simplify the syntax if you have a good suggestion

**Comment by imShara** [comment]
Thanks. Why command() need? I thought that was placeholder to example call python function. Why not just use colon:
`pqiv --bind-key="c:echo -n $1 | xclip -filter -selection clipboard"`
and for inner function:
`pqiv --bind-key="n:next_file()"`
where all string after ":" is command.
If command looks like `/^[A-z]+\(.*\)$/` - it's inner call if not - try call shell command

**Comment by phillipberndt** [comment]
The colon syntax wouldn't work because (a) it is possible to map a sequence of commands to a single key, e.g. "switch to fullscreen and return to the first image" and (b) it's possible to remap more than one key at once. Defaulting to interpreting the input as a shell command is too dangerous, imho. Also, it'd mean that if someone made a typo, pqiv couldn't tell but would only print an obscure shell syntax error when the user presses said key for the first time.

**Comment by imShara** [comment]
> it is possible to map a sequence of commands to a single key, e.g. "switch to fullscreen and return to the first image"

Where is the problem?
```
pqiv --bind-key="a:fullscreen();file(0)"
```
> it's possible to remap more than one key at once
```
pqiv --bind-key="a:fullscreen(); r:file(0)"
```
or more human-readable:
```
pqiv --bind-key="a:fullscreen()" --bind-key="r:file(0)"
```
> Defaulting to interpreting the input as a shell command is too dangerous, imho
You are already in the shell and writing shell command. Danger is here.

**PS.** [your solution](https://github.com/phillipberndt/pqiv/issues/47#issuecomment-267756863) is not working. There is "JFIF" string in clipboard  instead path.
```
pqiv -1 'echo -n $1 | xclip -selection clipboard' --keyboard-alias=c1 /home/user/image.png
/home/user/image.png

 pqiv --bind-key="c { command(echo -n $1 | xclip -selection clipboard)) }" /home/user/image.png
JFIF
```

**Comment by phillipberndt** [comment]
> Where is the problem?

The drawback of that approach is that the code you'll need to parse its syntax becomes inherently more complex. The current implementation can be parsed using a fairly simple top-down parser while yours requires an (arbitrarily large) look-ahead. The `r` from your second code block exemplifies that: You cannot tell whether it is part of a second command for `a` or part of a new key sequence until you parse the colon that follows it. The current implementation does not suffer from that issue because a command sequence is explicitly closed by a terminating symbol (the closing curly brace).

(You could now of course suggest to replace `{` with `:`, `;` with `,` and `}` with `;` to make the definitions look more like your examples. But that's then merely a matter of taste..)

> PS. your solution is not working. There is "JFIF" string in clipboard instead path.

Does you shell by any chance evaluate the `$1` if you use double quotes? Try using single ones instead:

     pqiv --bind-key='c { command(echo -n $1 | xclip -selection clipboard)) }' /home/user/image.png

**Comment by imShara** [comment]
> Try using single ones instead

Yep, i missed this. Problem was in quotes.

> code you'll need to parse its syntax becomes inherently more complex.

Not so. Anyway, you can't use lightweight splits and need to use smart parser, because any symbols can be part of the command (escaped too).

And you are right, it's a matter of taste, but i think that current solution is not natural.

**Comment by phillipberndt** [comment]
I've changed the code to make it easier to alter the syntax to one's personal taste. You can now simply use the patch

```diff --git a/pqiv.c b/pqiv.c
index 45a6d88..4271d78 100644
--- a/pqiv.c
+++ b/pqiv.c
@@ -428,9 +428,9 @@ GOptionEntry options[] = {
 
 #define  KEY_BINDINGS_KEY_TOKEN_BEGIN_SYMBOL           '<'
 #define  KEY_BINDINGS_KEY_TOKEN_END_SYMBOL             '>'
-#define  KEY_BINDINGS_COMMANDS_BEGIN_SYMBOL            '{'
-#define  KEY_BINDINGS_COMMANDS_END_SYMBOL              '}'
-#define  KEY_BINDINGS_COMMAND_SEPARATOR_SYMBOL         ';'
+#define  KEY_BINDINGS_COMMANDS_BEGIN_SYMBOL            ':'
+#define  KEY_BINDINGS_COMMANDS_END_SYMBOL              ';'
+#define  KEY_BINDINGS_COMMAND_SEPARATOR_SYMBOL         ','
 #define  KEY_BINDINGS_COMMAND_PARAMETER_BEGIN_SYMBOL   '('
 #define  KEY_BINDINGS_COMMAND_PARAMETER_END_SYMBOL     ')'```

to change the syntax to your preferred form. (Except for the closing semicolon, that is still required.)

**Comment by imShara** [comment]
Haha) A little bit compromise :)
