### ISSUE TITLE
--watch-directories With Images Downloading in the Background

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#49]
I've been trying having `pqiv --watch-directories` run for a directory under /tmp while aria2c downloads images in the background. It works okay, but I have to ensure that an image exists before starting pqiv or it will exit. Sometimes I want to clear all the images in the directory and then re-populate it with other images. This also can cause pqiv to close. Would it be possible to have pqiv stay open even in an empty directory (by default or with another option)?

Another problem is that pqiv will sometimes read an image before it is fully downloaded, causing it to fail and never be loaded. I'm not sure if there is a good way to deal with this though. I guess pqiv could retry reading failed images a few times, but for such a limited use case, it probably doesn't make sense to add that functionality. I realize that I can just pass pqiv a bunch of urls, but this is slow, and I want to be able to update/add to the images later.

**Comment by phillipberndt** [comment]
Regarding the first problem, this indeed is a bug, thanks for reporting it. If the last image is removed, pqiv ought to stay open. I'll fix that.

Regarding the second one, pqiv already waits for new files to be closed before trying to load them. My guess is that aria2c first allocates the space for the file and then downloads each chunk in separate threads/processes, resulting in no.-of-chunks+1 calls to close(). As a workaround, you could try if `--force-sequential` circumvents this problem, or download to a separate directory & move afterwards, or download to a temporary file name & rename after completion.

**Comment by noctuid** [comment]
Thanks for that information. Using `--stream-piece-selector=inorder` fixes that problem.

**Comment by noctuid** [comment]
So it doesn't seem that aria2c has an option to simply use some temporary extension until the download is completed. Downloading into a different directory and using `--on-download-complete` works fine though. Thank you for the suggestion.

**Comment by phillipberndt** [comment]
I've decided that fixing the issue of pqiv exiting without breaking other use cases would add too much complexity, and instead made this behaviour configurable.

By specifying `--watch-files=changes-only`, you can now configure pqiv to ignore if the current image is deleted. Note that this also applies to the two adjacent images, so when you replace all files, the *next* image in your slideshow will *once* still be one of the old ones.

**Comment by noctuid** [comment]
@phillipberndt Thank you for this option. It's a somewhat strange option though, so I think it might be better explained in the manpage by mentioning the effect on the adjacent images.

**Comment by phillipberndt** [comment]
Indeed. It's a corner case that calls for it, after all :smiley: I'll see to it that the documentation improves, thanks for the feedback!
