### ISSUE TITLE
About the --max-depth

### ISSUE THREAD

**Issue by gapplef** [phillipberndt/pqiv#55]
pqiv is a great command line tool! When I want use it as my default Image viewer, I encounter a problem:
when I use --browse, pqiv default load all images under the image's directory, including images in subdirectories, and
when --max-depth=1, pqiv will go into 1 levels of directories below current directory. That's reasonable, but
when --max-depth=0, pqiv will load only the one image I open.
So, how could I load the images in the current directory of the image I open(not include images in subdirectories), just like a normal Image Viewer.

**Comment by phillipberndt** [comment]
Which versions of the dependencies / or which distribution/os do you use? Here, `pqiv --max-depth=1 --browse image`, with `image` either as a relative path, absolute path or mere file name, all load all adjacent images within the same directory, but not from subdirectories.

**Comment by gapplef** [comment]
pqiv 2.2 @ Ubuntu 15.10
Sorry, forget to give these information

**Comment by phillipberndt** [comment]
Did you try the latest version? (The readme has a link to nightlies if you
don't want to build it yourself.)

Dylan Chen <notifications@github.com> schrieb am So., 10. Jan. 2016, 11:40:

**Comment by gapplef** [comment]
I just tried the latest version given in the link, it seems still have the problem.
max-depth=1will go into 1 levels of directories below current directory

**Comment by gapplef** [comment]
for directory, seems the behaviour is reasonable: max-depth=1 will go into just the given directory and not the subdirectories.
but for picture file, max-depth=1 will go into subdirectory of current directory.

**Comment by phillipberndt** [comment]
Funny. I had real trouble reproducing this in the morning, now it (didn't) work right away. The latest commit should fix the bug.

**Comment by gapplef** [comment]
Great! The problem is fixed. Really appreciate.
