### ISSUE TITLE
When trying to open a nonexisting file pqiv prints gibberish. 

### ISSUE THREAD

**Issue by onodera-punpun** [phillipberndt/pqiv#60]
It used to print `Failed to load archive sa: Error opening file: No such file or directory
No images left to display.`

Now it prints:
```

(pqiv:10289): GLib-GIO-CRITICAL **: g_file_info_get_size: assertion 'G_IS_FILE_INFO (info)' failed

(pqiv:10289): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Failed to load archive: Unrecognized archive format
No images left to display.
```

Introduced by this commit: https://github.com/phillipberndt/pqiv/commit/e2b62b377c514fbc64441092ad0594d5e71e6c78

**Comment by phillipberndt** [comment]
Thanks, fixed.
