### ISSUE TITLE
Support arbitrary image formats in archive files

### ISSUE THREAD

**Issue by phillipberndt** [phillipberndt/pqiv#61]
The current `archive_cbx` backend only works with GdkPixbuf, which is fine for the application of comic book files (which are zip files that should only contain jpg or png), but it should be easy to extend this to generic support for archive files.

From the backend's source code:

```
TODO:
This currently forceably uses gdkpixbuf to draw the contents. Since the
major format that this supports is cb*, which should only contain PNG/JPG.
this isn't much of an issue, but it would be nice to dynamically use other
backends. This currently does not work, at least not for backends that can
handle multi-page documents, because they expect to access image data by
either access to a memory region (which this backend can of course offer,
but keeping all archives as a whole in memory is not really a good solution)
or as something that can be accessed by an URI/filename. I'd have to
refactor this to support arbitrary callbacks, or finally bring myself to
use GIOs abstractions..
```

Some preliminary notes:
- There exists a [GMemoryInputStream](https://developer.gnome.org/gio/stable/GMemoryInputStream.html)
- Subclassing GFile [would be a long, tidious task](https://developer.gnome.org/gio/stable/GFile.html#GFileIface) and AFAIK no GFile representing a memory chunk exists so far
- Adding my own abstraction layer is perhaps (again) the easiest solution

**Comment by phillipberndt** [comment]
I went ahead and did a first implementation in 5c109db.

**Comment by noctuid** [comment]
Thanks! It seems to work perfectly with all the archives I've tried so far (zip, rar, tar.gz, and .7z).
