### ISSUE TITLE
Problem With Comments

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#62]
As an example, with this config file
```
[keybindings]
x { quit(); }
# this is a comment
```
I get this error
```
Failed to parse key bindings. Error in definition:
# this is a comment
                   ^-- here
Error was: Unexpected end of key binding definition
```

Also when I have a comment, for example, before `[options]` as the first line, pqiv will work but messages `Failed to load image #: Error opening file: No such file or directory`.

**Comment by phillipberndt** [comment]
Comments in the [keybindings] and global sections were deliberately not supported so far, because I thought people might try to bind `#` using `# { ... }` instead of `<numbersign>`. But I see that this creates more confusion than if any line starting with `#` was a comment. I hence changed the behavior. Thanks for the feedback & for testing this :+1:

**Comment by noctuid** [comment]
Thanks for the quick change.

**Comment by noctuid** [comment]
@phillipberndt Actually it seems that certain comment locations will still cause errors. For example,

```
[keybindings]
b { toggle_info_box(); }
# comment
g { goto_file_byindex(0); }
```
gives this
```
Failed to parse key bindings. Error in definition:
file_bto_file_byindex(0); }
                           ^-- here
Error was: Unexpected end of key binding definition
```

**Comment by phillipberndt** [comment]
I cannot reproduce this particular issue. Can you provide another, different example?

**Comment by noctuid** [comment]
```
[keybindings]
h { goto_file_relative(-1); }
i { goto_file_relative(1); }
<bracketleft> { goto_file_relative(-10); }
# comment
<bracketright> { goto_file_relative(10); }
```
gives
```
Failed to parse key bindings. Error in definition:
<bht> etright> { goto_file_relative(10); }
    ^-- here
Error was: Failed to parse key: `bht' is not a known GDK keyval name
```

This causes no error though:
```
[keybindings]
i { goto_file_relative(1); }
<bracketleft> { goto_file_relative(-10); }
# comment
<bracketright> { goto_file_relative(10); }
```

The original example with a trailing space or more words after `# comment` doesn't cause an error either.

**Comment by phillipberndt** [comment]
Apparently, github strips away the part that causes the problem. Could you paste the output of `base64 ~/.pqivrc`?

**Comment by phillipberndt** [comment]
A progress, I can reproduce the issue with the static 32bit build. Hang on..

**Comment by noctuid** [comment]
This is it:
W2tleWJpbmRpbmdzXQpoIHsgZ290b19maWxlX3JlbGF0aXZlKC0xKTsgfQppIHsgZ290b19maWxl
X3JlbGF0aXZlKDEpOyB9CjxicmFja2V0bGVmdD4geyBnb3RvX2ZpbGVfcmVsYXRpdmUoLTEwKTsg
fQojY29tbWVudAo8YnJhY2tldHJpZ2h0PiB7IGdvdG9fZmlsZV9yZWxhdGl2ZSgxMCk7IH0K

**Comment by phillipberndt** [comment]
Got it. I (wrongly) assumed that `strcpy` did not require non-overlapping memory areas. It should work now.

**Comment by noctuid** [comment]
Thanks for the fix!
