### ISSUE TITLE
Possible Extra Actions

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#63]
These are all the potentially useful extra actions and related behavior that I could think of. I put the ones I thought might be less useful towards the end. If you want, I can split these into separate issues for the ones you think would be worth adding.
# Most Useful
## Extra Scaling Actions

It would be cool if there were commands that would scale to the width or height of an image (or fit the image). Corresponding modes that would scale every image to the width, height, etc. could be nice. Also I'd love it if there was some way to preserve the zoom level between images (maybe as another scaling mode).
## Absolute X/Y Shift

Is there some way already to shift the image to an absolute position? The only reason I'd want this is to recenter the image after moving it.
## Cycle Actions

This would let the user make toggle keys. So for example, this could be used to cycle between a few different absolute scale levels. By the way, I noticed that `set_scale_level_absolute` is over-indented in the manpage. Another use case might be for having a key that would shift to specific corners/locations on the image and then jump to the next image for reading comics.
# Less Useful/Important
## Stepping Through Frames

An action to pause and step through gifs would be nice. It would also be nice if  "frame number/ total" was shown in the info bar.
## Change Speed

It could also be nice to have an action to change the play speed.
## Counts

Vim like counts could potentially be useful, but I don't know if it would be worth adding them. Sxiv works like this. For the most part, they would just repeat a command a number of times. For example, `4<space>` would jump 4 images forward. I honestly didn't often use sxiv's count feature except with `G`, which is an exception to the "repeat" behavior. It acts like `G` in vim, so `36G` would jump to the 36th image. An alternative for `G` specifically would be to have an interactive command to jump to an image by index (maybe modify `j`?). qiv has `jt<num>` to jump to an absolute image number and `jf<num>` and `jb<num>` for relative numbers. I don't think pqiv has an interactive command like this currently? The downside to this method is that an extra `<Return>` has to be pressed afterwards.

Related to G, I want to have a command to jump to the last index. I've tried `G { goto_file_byindex(0); goto_file_relative(-1); }`, but that doesn't seem to work.
## Jump to Previous Image

I occassionally used this in sxiv after an accidental jump to get back where I was. Other than for that, I don't know how useful it would be.
## Mark Actions

Sxiv has a command to mark images. It will keep track of the images so that they can be passed to some shell command. This functionality is already possible in pqiv by binding a key to append the image's filename to another file and then have a script get the file names from there. A dedicated mark command might be slightly easier to use. Another potential use case is that sxiv allows cycling through marked files and inverting the marked files (marking all unmarked files). Again, this is basically already possible when using pqiv with a file manager like ranger for marking, so I don't know if it would be all that useful to add.

**Comment by phillipberndt** [comment]
Wow, thanks, that's a lot of input :+1: I'll add the extra scaling options and absolute shift actions right away, and comment on the other stuff later (i.e. after releasing 2.5)

**Comment by phillipberndt** [comment]
I also added a way to make bindings cycle through different actions, though not a very convenient one:

e.g.,

    x { send_keys(#1); }
    <numbersign>1 { set_scale_level_absolute(1.); bind_key(x { send_keys(#2\); }); }
    <numbersign>2 { set_scale_level_absolute(.5); bind_key(x { send_keys(#3\); }); }
    <numbersign>3 { set_scale_level_absolute(0.25); bind_key(x { send_keys(#1\); }); }

**Comment by noctuid** [comment]
Awesome, I'll try this out when I get the chance. I like the `send_keys` idea. Another way might be to allow for named actions, so there wouldn't be be a need to bind dummy keys. The most convenient way would probably be to have some special syntax or action that would make a cycle behind the scenes, but I wouldn't mind using the current way.

You might also want to mention using `xev` to get special keynames in the manpage.

**Comment by phillipberndt** [comment]
Some more feedback on your other points:

Stepping through frames & changing speed of animation sounds quite useful, I'll add this for the next version.

Regarding counts, modifying `j` to also search within the index column sounds
reasonable, or to search only within the index column if e.g. `#<number>` is
entered. As for vim-like counts, I don't see that the benefits would justify
the effort. I also believe that it is hard to implement this without breaking the
ability to rebind the number keys.

I already added a command to jump to the last file, see the latest commit above. Btw. `G { goto_file_byindex(0); goto_file_relative(-1); }` works for me!?

Regarding keeping track of the last image viewed, that shouldn't add too much overhead (should be 7 SLOC including the action to return to it), I'll think about that.

Finally, regarding the option to mark images, I believe that this isn't worth the effort, since, as you've said, this is already possible.

**Comment by noctuid** [comment]
> As for vim-like counts, I don't see that the benefits would justify
the effort.

I guessed as much. I don't know how often one would want to search for numbers in an image. Maybe it could be made so that `j` will search by the index if only numbers have been entered or at least give the index a higher priority in that case.

> G { goto_file_byindex(0); goto_file_relative(-1); } works for me!?

It does for me too. The problem before was that I wasn't using `<Shift>g`. Then new syntax to do it in one command is nice though; thank you.

Also, are you planning on adding the other scaling commands (for automatically scaling to each image's width or height or just doing so for a single image)? In addition to `set_scale_mode_fit_px(x, y)`, I'd really like something like a `set_scale_mode_maintain_level` that would maintain the current scale percentage/level for other images.

Thanks a lot for the cycling. I'm emulating having named actions by doing `<key> { send_keys(:name); ... }` which is pretty readable. As for the absolute shifting actions, they don't seem to do anything for me regardless of what values I use (e.g. `m { set_shift_x(0); set_shift_y(0); }` after shifting an image does nothing). Also, I think it would be awesome if there were some alignment commands to allow for the corner cycle I mentioned previously. For example:

```
# align top left corner of image with top left corner of window
align_left(); align_top();
# act same as set_shift_x(0); set_shift_y(0);
align_center();
# align bottom right corner of image with bottom right corner of window
align_right(); align_bottom();
```
What do you think? Even more precise alignment could be done if there were absolute shift actions that would shift based on a percentage of the image size, but that's probably overkill.

**Comment by phillipberndt** [comment]
> Also, are you planning on adding the other scaling commands (for automatically scaling to each 
> image's width or height or just doing so for a single image)? In addition to set_scale_mode_fit_px(x, 
> y), I'd really like something like a set_scale_mode_maintain_level that would maintain the current 
> scale percentage/level for other images.

`set_scale_mode_fit_px` *does* change the scale mode for all images to fit the given dimensions.  `set_scale_mode_maintain_level` is *almost* there, I only forgot to make the option accessible through the actions. It is now, via `toggle_scale_mode(4)`.

> As for the absolute shifting actions, they don't seem to do anything for me

Your `m` example works for me!

> Also, I think it would be awesome if there were some alignment commands to allow for the corner cycle I mentioned previously.

Yes, that sounds like a good thing to have. I could add this as `set_shift_align_corner`, with cardinal directions as parameters (e.g. `NE` to align the upper right corner.)

**Comment by noctuid** [comment]
> set_scale_mode_fit_px does change the scale mode for all images to fit the given dimensions.

The dimensions are in pixels though, so I couldn't use this to fit individual images to either their full height or width. Or is there some way to do that?

> It is now, via toggle_scale_mode(4)

Awesome, thank you.

> Your m example works for me!

After updating, it was working for me. I had just updated before, so I have no idea what was happening.

> I could add this as set_shift_align_corner, with cardinal directions as parameters (e.g. NE to align the upper right corner.)

That would be great.

**Comment by phillipberndt** [comment]
> The dimensions are in pixels though, so I couldn't use this to fit individual images to either their full 
> height or width. Or is there some way to do that?

`set_scale_level_absolute(1)`?

**Comment by noctuid** [comment]
> set_scale_level_absolute(1)?

I mean have the width of the image match the width of the window, so it wouldn't usually be at 100%. As for the scaling modes, is there some way to choose the dimensions/percentage of the window they scale down or up to?

Also, I edited my previous comment.

**Comment by phillipberndt** [comment]
I see. Neither of this is currently possible. pqiv is designed to match the scaled image size and window size, and every possibility there currently is to avoid that that is merely there to smoothen out the  issues this creates with some WMs. I'll look into this as well.

**Comment by noctuid** [comment]
> match the scaled image size and window size

Ah, with openbox it changes the window size for me. I'm using a tiling window manager, so I didn't know. If I put pqiv in fullscreen it scales down as I would expect it to. That's good to know.

**Comment by phillipberndt** [comment]
I added `set_shift_align_corner`, and also considered your EDIT - you can do this by adding another `C` (for center) in front, e.g. `set_shift_align_corner(CNE)` will prefer to center the image, but align north east if its dimensions exceed the available space.

**Comment by noctuid** [comment]
Thanks, they're working brilliantly! I was thinking I might like to bind a key to go to the next image and align it at the top, but with `{ goto_file_relative(1); set_shift_align_corner(CN); }`, the alignment will happen for the current image. Could there be some way to delay this until the next image is loaded?

**Comment by phillipberndt** [comment]
I thought about that as well, and there is now, but I am uncertain how reliable the implementation is. See the [lengthy comment in the commit above](https://github.com/phillipberndt/pqiv/commit/4439874404c1e3a35fcc6b6fd277ef1fdd40d4b1#diff-6b008e9d53b34fbc2bd678af46b85de9R3236).

**Comment by phillipberndt** [comment]
I've merged the step through frames / change animation playback speed changes into master to enforce testing.

**Comment by noctuid** [comment]
Thanks! It seems to work great from what I've tried. Could it be possible to step in reverse as well?

As for the previous change (going to a file and then aligning), it seems to generally work for me. Sometimes it won't work though. It's rare if I'm advancing slowly, but if I hold my "next image" key down, it will fail a lot more frequently.

**Comment by phillipberndt** [comment]
> Thanks! It seems to work great from what I've tried. Could it be possible to step in reverse as well?

Sadly, no. The [`gdk_pixbuf_animation_iter_advance`](https://developer.gnome.org/gdk-pixbuf/2.23/gdk-pixbuf-Animations.html#gdk-pixbuf-animation-iter-advance) documentation explicitly states that "*you can't go backward in time; animations only play forward*". That wouldn't prevent me from still implementing this for the other backends, but since pqiv is primarily intended as an image viewer, I'd consider that an overkill (for now).

> As for the previous change (going to a file and then aligning), it seems to generally work for me. 
> Sometimes it won't work though. It's rare if I'm advancing slowly, but if I hold my "next image" key 
> down, it will fail a lot more frequently.

That is insofar to be expected as I deliberately made the actions that change the current image responsive even while pqiv is occupied with loading a new image. If I wouldn't then loading a huge image would block pqiv completely and leave you with the previous image until the large one has finished loading. Also, pqiv doesn't have a queue for outstanding actions. Instead, pressing a key always immediately ends processing of the actions associated with the key that you've pressed earlier.

As a consequence, if you press the "next image" key rapidly, you can (and obviously do) hit the race condition that pqiv already started processing the latest key press when it finished loading an image that you already told it to navigate away from. The code that draws that image then sees that you've requested to draw it at the top of the window, does so and marks the action chain as done. When the new image that the alignment command was actually intended for is then eventually loaded, it won't be aligned anymore.

I think that I might come up with a mitigation, but it won't be a nice one.. hence the question: Is this a problem you run into regularly, that is, one that you feel needs to be fixed, or is it one that you could live with because it doesn't affect you in practise?

**Comment by noctuid** [comment]
>  Is this a problem you run into regularly, that is, one that you feel needs to be fixed, or is it one that you could live with because it doesn't affect you in practise?

If there was a non-hacky way to do it by adding actions to a queue to be run after an image is loaded, it would be nice, but it sounds like this isn't easy to do. I think it's a really minor issue that almost never causes me any problems, so I don't think it's worth the trouble to fix.

**Comment by phillipberndt** [comment]
There might be an easy way after all.. do the changes from the [block-chain-while-loading](https://github.com/phillipberndt/pqiv/tree/block-chain-while-loading) resolve this issue?

**Comment by noctuid** [comment]
Yes, that branch seems to fix the issue completely for me.

**Comment by phillipberndt** [comment]
Great. Merged to master. Also, I've added the "Jump to Previous Image" action you've requested. Since I already call the image with index (n-1) the previous image, I went with the terminology "earlier image". The action is by default mapped to `Ctrl-R`.

With that, this issue should be resolved! :-)

**Comment by noctuid** [comment]
Awesome, thanks for all the new functionality.
