### ISSUE TITLE
Uppercase Letter Keybindings

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#64]
I mentioned this in the last issue I made not realizing this was the problem. I'm not able to bind uppercase letters:

```
[keybindings]
h { goto_file_relative(-1); }
H { shift_x(-10); }
```
Pressing `H` with this config will will move to the previous file. I've also tried using `<H>`.

**Comment by phillipberndt** [comment]
It's <Shift>H. The distinction is intentional, but I should probably at
least a heuristic to autocorrect the missing <Shift>.

noctuid <notifications@github.com> schrieb am So., 20. März 2016, 23:56:

**Comment by noctuid** [comment]
That makes sense; I'm just used to not having to specify shift for letters in keybindings. Thanks for the change.
