### ISSUE TITLE
request for homebrew formula

### ISSUE THREAD

**Issue by ronubi** [phillipberndt/pqiv#66]
Can you provide a homebrew formula for pqiv, so we can install it easily on Mac?

Thanks in advance.

**Comment by phillipberndt** [comment]
I unfortunately do not have a mac, and no experience with homebrew. There's [a tutorial on how to make formulas](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md) on the Homebrew homepage though. It looks simple enough. Here's a version that *might* work:

    class Pqiv < Formula
    	desc "Minimalist image viewer inspired by qiv"
    	homepage "https://github.com/phillipberndt/pqiv"
    	url "https://github.com/phillipberndt/pqiv/archive/2.5.1.tar.gz"
    	sha256 "de027c5ebab80a19066e3a891edf76c58ba1622e45227db380349eec214898bc"
    
    	depends_on "pkg-config" => :build
    	depends_on "glib"
    	depends_on "gtk+"
    	depends_on "gdk-pixbuf"
    	depends_on "cairo"
    	depends_on "libspectre" => :recommended
    	depends_on "poppler" => :recommended
    	depends_on "imagemagick" => :recommended
    	depends_on "libarchive" => :recommended
    	depends_on "ffmpeg" => :optional
    
    	def install
    		system "./configure", "--prefix=#{prefix}"
    		system "make", "install"
    	end
    end

If it does, or you manage to make it work, I'd appreciate if you'd [submit it to homebrew-core](https://github.com/Homebrew/homebrew-core))!

**Comment by phillipberndt** [comment]
I've updated the above formula for 2.6.

**Comment by ronubi** [comment]
Thanks.  I tried to follow the homebrew build instructions, but got multiple errors.  I have never created or pushed packages to homebrew-core. I might try installing pqiv from source, the old-fashioned way, to see if there's something basic that isn't working on my Mac . . .

**Comment by phillipberndt** [comment]
Hi, are you still interested in a Homebrew formula?

I still cannot debug this on my own, but if you provide the error messages, I might be able to come up with a solution. I did another update to the candidate formula above. I also have a suspicion on what might go wrong (namely that the X11 headers are likely missing - this should be resolvable by simply removing the functionality from pqiv).

**Comment by phillipberndt** [comment]
Closing this for now, as I cannot test this and no one seems to be interested in it currently.

**Comment by phillipberndt** [comment]
With the help of @maikel, I've been able to fix the formula. The above formula works now, and I'll submit it to homebrew-core upon the next release of pqiv (which is scheduled for this weekend).

**Comment by phillipberndt** [comment]
Formula submitted upstream; from here on, this is out of my hands :-)

You can always use the formula from above and brew's `--HEAD` version to install the latest pqiv version.

**Comment by phillipberndt** [comment]
FYI, this is now included in homebrew-core, so pqiv should be installable using `brew install qpiv`. There's also support for `--HEAD`.

**Comment by maikel** [comment]
> FYI, this is now included in homebrew-core, so pqiv should be installable using `brew install qpiv`. There's also support for `--HEAD`.

`brew install pqiv`
