### ISSUE TITLE
Some pdfs don't open with pqiv

### ISSUE THREAD

**Issue by onodera-punpun** [phillipberndt/pqiv#67]
This one for example https://punpun.xyz/Xl6N.pdf

```
pqiv 'Mencius - Mencius.pdf'
No images left to display.
```

green, https://github.com/schandinat/green, also using poppler opens it just fine, so I'm not sure what's going on.

**Comment by phillipberndt** [comment]
This appears to depend on the Poppler version. It works fine here on my local system using 0.24.5. The [nightly](http://page.mi.fu-berlin.de/pberndt/pqiv-builds/pqiv-master-2.5.1-2-g161c4bc-static-linux-i386), on the other hand, does not.

I'll look into that. Thanks.

**Comment by phillipberndt** [comment]
I just tested this with poppler-0.45.0: The new version of poppler claims that "PDF document is damaged". pqiv's bug is that it does not output the error message that's missing. I'll fix that. In the meantime, it'd make sense to file a bug against poppler with the PDF attached?!

**Comment by phillipberndt** [comment]
See https://bugs.freedesktop.org/show_bug.cgi?id=96884
