### ISSUE TITLE
Add option to wait for images to appear

### ISSUE THREAD

**Issue by phillipberndt** [phillipberndt/pqiv#76]
@emdete suggested in #74:

> another thing: pqiv should allow to start/encounter empty directories (showing black) and start when images appear (at least with --watch-directories), currently it terminates with No images left to display..

This should not be the default, because it'd break backwards compatibility, but having an option for this is a great idea.

**Comment by phillipberndt** [comment]
This was much easier than I initially thought - I might even include this in 2.7 because it's so simple. See the [wait-for-images](https://github.com/phillipberndt/pqiv/compare/wait-for-images) branch. @emdete, does (except for your network FS problems) the `--wait-for-images-to-appear` work as you'd expect it to do?

**Comment by emdete** [comment]
sorry, had no time to test that earlier. it works great with a small drawback: the window is shown when the first picture apears. before no window is opened and the screen is shown. this could make problems if the active screen changes after starting qpiv so the window apears on the wrong screen.

**Comment by phillipberndt** [comment]
That was intentional, but having this as an option certainly is beneficial. See the updated branch: The new option `--allow-empty-window` does what you want, and it also prevents pqiv from exiting if it fails to load any image. Note that due to the repositioning after loading images, the window may still jump screens depending on which WM you are using. You can disable this feature using `--window-position=-1,-1`. Use this command line to test the feature:

    ./pqiv --watch-directories --allow-empty-window --lazy-load --wait-for-images-to-appear --window-position=-1,-1 <directory>

**Comment by emdete** [comment]
wow, that's it. it even notices if the image(s) disapear and goes back to black. very nice and exactly my expectation! :D

**Comment by noctuid** [comment]
Thanks for these new options! They also makes some of the issues I had that I mentioned in #49 simpler to deal with (mainly I don't have to use inotifywait to wait to open pqiv now).

**Comment by phillipberndt** [comment]
Good to hear. See also #77, which should allow you to manually rescan the
network share using the add_file action. (It will add images that are
already loaded as well though.)
