### ISSUE TITLE
Build failing with gtk2

### ISSUE THREAD

**Issue by daniloegea** [phillipberndt/pqiv#78]
I'm trying to build pqiv 2.7 with gtk2 and it's failing with the following error:
pqiv.o: In function `window_screen_changed_callback':
pqiv.c:(.text+0x840a): undefined reference to `GDK_IS_X11_DISPLAY'
cc: error: linker command failed with exit code 1 (use -v to see invocation)

With gtk3 it works fine though.

**Comment by phillipberndt** [comment]
Dang. Thanks; testing GTK 2.0 on Linux slipped my mind :roll_eyes: Fixed in 2.7.1.
