### ISSUE TITLE
Moving to next image resets zoom level

### ISSUE THREAD

**Issue by bearcatsandor** [phillipberndt/pqiv#81]
If increase the zoom level while a pdf or a list of images is loaded, when i migrate to the next page/image the zoom level resets to the initial value when i loaded the file(s).

It would be great to retain zoom levels between files and pages.

**Comment by noctuid** [comment]
You can use `toggle_scale_mode(4)` for this ("4 to maintain the user-set zoom level" from the manpage).

**Comment by bearcatsandor** [comment]
Thank you noctuid. I consider myself experienced at reading man pages, but i'm stumped by this one. If I zoom in, press 4 to set that zoom level, then activate my mouse wheel to go to the next image, the zoom level resets. The same behavior occurs if i press 4, zoom in then activate my mouse wheel.

What i want is to retain the zoom level as a default behavior, probably though a command line switch of some sort or the user config file. How can i accomplish this?

**Comment by noctuid** [comment]
Did you bind it to `4`? I don't think it's bound by default (I'd have to check), but you have to bind the action to a key. If you want it to happen by default, you can use `--action` or put the action under the `[actions]` section in your config:

```
...
[actions]
toggle_scale_mode(4)
```

**Comment by bearcatsandor** [comment]
Putting that lin in my config did the trick! Thank you so much.

**Comment by phillipberndt** [comment]
@bearcatsandor Please let me know if you have a good idea on how I could improve the documentation.

Also, while I won't include this in the default `t` rotation, I can perfectly imagine binding this to a different key, like `C-t`, by default. Let me know if you'd like that.

**Comment by bearcatsandor** [comment]
I would like that, thank you for the quick response.

**Comment by phillipberndt** [comment]
Done.
