### ISSUE TITLE
Set color of infobox on command line

### ISSUE THREAD

**Issue by bearcatsandor** [phillipberndt/pqiv#83]
Allow us to set the color of the infobox via the commandline so that it better matches our environments.

**Comment by phillipberndt** [comment]
Sure, that's simple enough. See the `infobox-color` branch.

**Comment by bearcatsandor** [comment]
Thank you very much! I'll test it out.

**Comment by phillipberndt** [comment]
I've updated this to work for montage mode as well, and renamed the option to `--box-colors`.

**Comment by noctuid** [comment]
I'd like to see this feature in 2.9. Thanks for the update; I will test it later today.

**Comment by noctuid** [comment]
It's working as expected for me. I haven't encountered any problems.

**Comment by phillipberndt** [comment]
Thanks. I've merged the changes to master.
