### ISSUE TITLE
1-9 Commands Cannot be Defined in .pqivrc

### ISSUE THREAD

**Issue by 8BitAce** [phillipberndt/pqiv#84]
**Steps to reproduce:**
1. Create a .pqivrc with the following content:
```
[options]
command-2=touch foo.txt
```
2. Run pqiv and press the 2 key

**Result:**
pqiv says it's executing the command, but nothing happens. Looking in the console you'll see something like ```/bin/sh: 2hy5lklr5wgy.jpg: command not found```

It seems that no matter what is entered for such a command, the image name is always passed to the shell instead of what you put in the config.

**Comment by phillipberndt** [comment]
Thank you very much for reporting this. I've fixed this in master and release 2.8.3 with the fix cherry-picked shortly.
