### ISSUE TITLE
Scale-Down Option

### ISSUE THREAD

**Issue by 8BitAce** [phillipberndt/pqiv#85]
Really loving pqiv as command-line image viewer. Only thing I've found missing is better support for tiling window managers. Currently if I put pqiv into a tiled layout the image doesn't change when going forward/backward through the list (though the window title does change). I highly suspect this is due to pqiv requesting a window size change but the window manager keeping it fixed.

Feh has an option to overcome this by keeping the window geometry the same and scaling down larger images to fit, with the rest of the window filled with a pattern (though transparency would be interesting). I'll copy the entry from the feh man page here:
```
-., --scale-down
        Scale images to fit window geometry (defaults to screen size when no geometry was specified). Note that the window geometry is not updated when changing images at the moment.
        This option is recommended for tiling window managers.  This option is ignored when in fullscreen mode.

        In tiling environments, this also causes the image to be centered in the window.

```

Do you think it would be possible to add such a feature in pqiv? It would definitely be useful!

**Comment by phillipberndt** [comment]
Pqiv does have this feature & should scale down automatically. I used to
use i3 and tested this explicitly while developing it. Which WM do you use?

I'll be on vacation throughout March but will attempt to fix this when I
come back.

**Comment by 8BitAce** [comment]
Hmm, odd. I'm using Awesome 4.0 and specifically the standard tiled layout.
Definitely no hurry, thanks for this awesome project!

**Comment by phillipberndt** [comment]
I've managed to reproduce this - it's a weird bug and I strongly suspect that it is one in GTK or Awesome WM. I explicitly call `gtk_widget_queue_draw`, but it is completely ignored as long as the window's size doesn't change. Even if I manually replace the call with

	// Hack: Draw NOW!
	printf("Redraw NOW!\n");
	gdk_window_invalidate_rect(gtk_widget_get_window(GTK_WIDGET(main_window)), NULL, TRUE);
	gdk_window_process_all_updates();

which according to the GTK source code does redraw the window immediately, it doesn't work. I really don't know what I could do to fix this.

Workarounds:

* Only GTK 3 is affected, GTK 2 works fine.
* Run pqiv in a floating window, this seems to work as expected for me.
* Use `--recreate-window`. It's ugly, but it works.

**Comment by 8BitAce** [comment]
Ah, well thanks for looking into it so thoroughly! I had a suspicion that was the case once you said it works correctly in i3. At least it's reproducible. I'll try to file an issue against Awesome instead then. You can go ahead and close this if you'd prefer.

Thanks!

**Comment by phillipberndt** [comment]
All right. Please reference this bug from the Awesome bug report, I'll follow it as well to see if there's any viable workaround that I could add to pqiv which I've missed.
