### ISSUE TITLE
Handle archives as directories

### ISSUE THREAD

**Issue by pa-d-v** [phillipberndt/pqiv#94]
When showing images in a zip archive the archive should be handled as a directory meaning Control Space and Control Backspace should move to the next or previous directory/archive. Currently Control seems to be ignored for images in an archive and the next or previous image is shown.

**Comment by phillipberndt** [comment]
What if an archive contains multiple directories? There'd be a 3-fold ambiguity then: You could either want to jump to the next directory within the archive, to the next archive, or to the next outer directory.

**Comment by pa-d-v** [comment]
I look at it like the jump list: Control Space should move forward to the next folder in this list and Control Backspace backwards. So it should jump to the next directory within the archive.

**Comment by phillipberndt** [comment]
Would you mind if you'd need a different key combination to do that? I could easily add two new navigation actions, like `next_physical_file` (to jump to the next archive) and `next_logical_folder_within_file` (to jump to the next folder), and corresponding `previous_..` actions.

**Comment by pa-d-v** [comment]
Would become very difficult then for a user to know which keys to press with a mix of directories and archives. Control Space should just move to the next logical of physical folder and Control Backspace to the previous.

**Comment by phillipberndt** [comment]
True. `next_logical_folder`, and regarding archives as folders, sounds like a good compromise. I'll work on it.

**Comment by phillipberndt** [comment]
See the `next-logical-dir` branch. I've also changed the default key binding to use this navigation type instead of physical directory movement.

**Comment by pa-d-v** [comment]
Works perfectly, thanks!

**Comment by phillipberndt** [comment]
Great. Merged to master.
