### ISSUE TITLE
Adjusting transparency of the image

### ISSUE THREAD

**Issue by mertyildiran** [phillipberndt/pqiv#95]
Is it possible to adjust the transparency of the image? I mean an option like this would be very helpful:

```
pqiv -c -i image_with_alpha.png --alpha 0.5
```

**Comment by phillipberndt** [comment]
Sure, that's easy enough. But I won't include this in pqiv, because the use case is a bit too obscure. (..and because you can do this using a compositing WM, too. Most WMs support adjusting windows' alpha values these days.) Here's how to do it:

```patch
diff --git a/pqiv.c b/pqiv.c
index fcfd3b7..05d62f9 100644
--- a/pqiv.c
+++ b/pqiv.c
@@ -292,6 +292,7 @@ gboolean option_sort = FALSE;
 enum { NAME, MTIME } option_sort_key = NAME;
 gboolean option_shuffle = FALSE;
 gboolean option_transparent_background = FALSE;
+gdouble option_alpha = 1.0;
 gboolean option_watch_directories = FALSE;
 gboolean option_wait_for_images_to_appear = FALSE;
 gboolean option_fading = FALSE;
@@ -404,6 +405,7 @@ GOptionEntry options[] = {
        { "command-9", '9', G_OPTION_FLAG_HIDDEN, G_OPTION_ARG_STRING, &external_image_filter_commands[8], NULL, NULL },
 #endif
 
+       { "alpha", 0, 0, G_OPTION_ARG_DOUBLE, &option_alpha, "Adjust window's alpha", NULL },
 #ifndef CONFIGURED_WITHOUT_ACTIONS
        { "action", 0, 0, G_OPTION_ARG_CALLBACK, &option_action_callback, "Perform a given action", "ACTION" },
        { "actions-from-stdin", 0, 0, G_OPTION_ARG_NONE, &option_actions_from_stdin, "Read actions from stdin", NULL },
@@ -4944,7 +4946,7 @@ gboolean window_draw_callback(GtkWidget *widget, cairo_t *cr_arg, gpointer user_
                        // to speed up rotations on scaled images
                        cairo_surface_t *temporary_scaled_image_surface = get_scaled_image_surface_for_current_image();
                        cairo_set_source_surface(cr, temporary_scaled_image_surface, 0, 0);
-                       cairo_paint(cr);
+                       cairo_paint_with_alpha(cr, option_alpha);
                        cairo_surface_destroy(temporary_scaled_image_surface);
                }
```

Mind that this implementation does not work with `--low-memory`.

**Comment by mertyildiran** [comment]
@phillipberndt could you suggest a solution rather than modifying your project? Because shipping it would be so hard for me... I mean I see you are using [cairo](https://www.cairographics.org/) but [pycairo](https://github.com/pygobject/pycairo) seems like immature. Can you suggest me a library, another binding of cairo or something like that?

**Comment by phillipberndt** [comment]
To achieve what? Placing a watermark on top of an X11 screen such that mouse events pass through? Or do you plan to use any other feature of pqiv?

**Comment by mertyildiran** [comment]
> Placing a watermark on top of an X11 screen such that mouse events pass through?

Yes, this is exactly what I'm looking for :blush: Sorry for opening multiple issues by the way. I thought they are separate subjects so I opened two issues.
