### ISSUE TITLE
Displaying the image without blocking mouse events

### ISSUE THREAD

**Issue by mertyildiran** [phillipberndt/pqiv#96]
Is there a way to display the image without blocking mouse events? I mean, I would like to be able to click things inside the window that just behind the image. Imagine that we are displaying the image like a watermark on the screen. Is there a way to do that?

**Comment by phillipberndt** [comment]
Tricky. This definitively depends on your desktop environment - I'm assuming you're running pqiv under X11? Do you want the whole window to be "click-through", or just the transparent part? (The latter is easy, the former requires you to manually pass the events to the underlying window, which requires some Xlib hacking)

**Comment by mertyildiran** [comment]
@phillipberndt yes, I'm looking that for Ubuntu based distros (I think that means X11 Window System).

If you provide the information for both of the scenarios then I would be so happy :blush: Because if hard option is too hard then I can go just transparent option. Also the image can be semi-transparent if it helps...

**Comment by phillipberndt** [comment]
Turns out that it's not so simple with semitransparent parts either. That makes the other solution simpler, actually. [See this SO thread](https://stackoverflow.com/questions/16400937/click-through-transparent-xlib-windows) for what must be done. Actually, if you don't plan to use pqiv for anything else, I think that writing a plain Xlib application might be the simplest solution, because you can then simply feed the Xlib events directly back into the `XSendEvent` call. (And since you mentioned Python, Xlib has [working Python bindings](http://python-xlib.sourceforge.net/).)

**Comment by mertyildiran** [comment]
@phillipberndt thank you so much! :blush: I wasn't even know where to look. Now I will make some research about **Xlib**. Thanks for enlightening me.

**Comment by phillipberndt** [comment]
All right. Let me know if you're stuck, maybe I can help..

**Comment by mertyildiran** [comment]
@phillipberndt I just found [this blog](http://shallowsky.com/blog/programming/translucent-window-click-thru.html) post and from that blog post I found [this Gist](https://gist.github.com/akkana/3f0ca0f3be5e61f2f7c67db76fd8deb8). It's able create a click-through region inside the window.

![](http://i.imgur.com/ZHwy1zL.png)

(*Light green region is click through*)

If it's not Always on Top then it will minimize so make it Always on Top using your system dialog:

![](http://i.imgur.com/rJC1KqR.png)

Now there are only two things I should achieve **drawing the image** and making it **Always on Top**. Could you help me about drawing the image? At the end of the day we will be able to bring real HUD to linux :trophy:

**Comment by phillipberndt** [comment]
That's useful. Here's a patch to apply this to pqiv:

```patch
diff --git a/GNUmakefile b/GNUmakefile
index 1127864..ac43446 100644
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -95,7 +95,7 @@ endif
 
 # We need X11 to workaround a bug, see http://stackoverflow.com/questions/18647475
 ifeq ($(filter x11, $(shell pkg-config --errors-to-stdout --variable=target gtk+-$(GTK_VERSION).0; pkg-config --errors-to-stdout --variable=targets gtk+-$(GTK_VERSION).0)), x11)
-       LIBS+=x11
+       LIBS+=x11 xext
 endif
 
 # Add backend-specific libraries and objects
diff --git a/pqiv.c b/pqiv.c
index fcfd3b7..f9a8e54 100644
--- a/pqiv.c
+++ b/pqiv.c
@@ -56,6 +56,7 @@
 #ifdef GDK_WINDOWING_X11
        #include <gdk/gdkx.h>
        #include <X11/Xlib.h>
+       #include <X11/extensions/shape.h>
        #include <cairo/cairo-xlib.h>
 
        #if GTK_MAJOR_VERSION < 3
@@ -4944,7 +4945,7 @@ gboolean window_draw_callback(GtkWidget *widget, cairo_t *cr_arg, gpointer user_
                        // to speed up rotations on scaled images
                        cairo_surface_t *temporary_scaled_image_surface = get_scaled_image_surface_for_current_image();
                        cairo_set_source_surface(cr, temporary_scaled_image_surface, 0, 0);
-                       cairo_paint(cr);
+                       cairo_paint_with_alpha(cr, .5);
                        cairo_surface_destroy(temporary_scaled_image_surface);
                }
 
@@ -6360,6 +6361,16 @@ gboolean window_configure_callback(GtkWidget *widget, GdkEventConfigure *event,
        }
        #endif
 
+       // Adjust shape
+       Display *display = GDK_SCREEN_XDISPLAY(gdk_screen_get_default());
+       unsigned long window_xid = gdk_x11_window_get_xid(gtk_widget_get_window(GTK_WIDGET(main_window)));
+       Region region = XCreateRegion();
+       XRectangle rectangle = { 0, 0, 1, 1 };
+       XUnionRectWithRegion(&rectangle, region, region);
+       XShapeCombineRegion(display, window_xid, ShapeInput, 0, 0, region, ShapeSet);
+       XDestroyRegion(region);
+
+
        return FALSE;
 }/*}}}*/
 void handle_input_event(guint key_binding_value);
@@ -6883,6 +6894,8 @@ void create_window() { /*{{{*/
        if(option_transparent_background) {
                window_screen_activate_rgba();
        }
+
+       gtk_window_set_keep_above(main_window, TRUE);
 }/*}}}*/
 gboolean initialize_gui() {/*{{{*/
        setup_checkerboard_pattern();
```

To make an Xlib application stay on top, see [this SO answer](https://stackoverflow.com/a/16235920/1881610). To draw an image, see [this one](https://stackoverflow.com/a/6401801/1881610), though it might be simpler [to use an external library like cairo](https://cairographics.org/Xlib/) for that.

**Comment by mertyildiran** [comment]
@phillipberndt that's working perfectly, thank you so much! :trophy: 

Now the problem is how can I integrate this into our project [Dragonfire](https://github.com/DragonComputer/Dragonfire). I compiled [click-through](https://gist.github.com/akkana/3f0ca0f3be5e61f2f7c67db76fd8deb8) with distutils/setuptools. But when I import the library with `import realhud` I'm getting this error:

```
ImportError: /home/mertyildiran/Downloads/realhud-test/realhud.so: undefined symbol: XLookupString
```

Try it yourself, clone [this repository](https://github.com/Old-But-Gold/realhud-test) and install it `sudo pip install -e .`

I'm also considering the option that compiling and installing a modified version of your project **pqiv** on post-installation but I'm not sure what's the best option.

Could you please to join [our Gitter chat room](https://gitter.im/DragonComputer/Lobby) and guide me about what to do? OR you could even choose to integrate that feature to **Dragonfire** by yourself and send a PR. I would be so glad to see you as a contributor. :blush:

**Comment by phillipberndt** [comment]
> But when I import the library with `import realhud` I'm getting this error

Works like a charm here. The message indicates that the library isn't liked to Xlib:

    $ ldd realhud.so
    ...
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8bce41e000)

should be missing for you. I don't really understand why though, your setup.py looks fine to me. If you build verbosely (`setup.py build -v` after deleting the `build` folder), does the last line linking the final shared object contain `-lX11` *after* `realhud.o`?

**Comment by mertyildiran** [comment]
@phillipberndt Interestingly installing it with `setup.py build` and `setup.py install` now it's working :smile: 

If I face with problems while drawing the image then I will knock your door again, thank you so much! :+1:  :blush:

**Comment by mertyildiran** [comment]
@phillipberndt I have implemented a simple version of your program (by following your suggestions) in [here](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/realhud/realhud.c), please take a look....

and this avatar/visualization is the result of that program:

![](https://github.com/DragonComputer/Dragonfire/raw/master/docs/img/demo.gif)

Many thanks for your support :trophy:

**Comment by mortoray** [comment]
Did any of this feature make it into `pqiv`? I'd really like to have click-through windows.

**Comment by mortoray** [comment]
I added the potential patch in a PR in case somebody is interested. I'll be using this patched version.

**Comment by mertyildiran** [comment]
@mortoray I was thinking about would it be possible to combine this idea with HTML rendering. Imagine that there is a library that can render HTML elements with transparent background and click-trough window which would be a cool solution for displaying a gauge CPU meter or a complete HUD overlay just like in FPS games:

![](https://www.researchgate.net/profile/Rennan_Raffaele/publication/318572588/figure/fig37/AS:518271940399110@1500577067478/Overwatch-game-McCree-first-person-view-78.jpg)

**Comment by phillipberndt** [comment]
@mertyildiran [Check out this SO question](https://stackoverflow.com/questions/324923/is-it-possible-to-render-web-content-over-a-clear-background-using-webkit).

**Comment by mertyildiran** [comment]
@phillipberndt does [that SO answer](https://stackoverflow.com/a/1133455/2104879) met the **click-trough window** criteria?

By click-trough I mean not just a click-trough HTML element but the whole window is click-trough. Just like the behaviour you and I (mostly you though :laughing:) achieved a year ago.

**Comment by phillipberndt** [comment]
No, but you can easily combine the two, the change required to the code from the SO should be roughly the same.

**Comment by mertyildiran** [comment]
@phillipberndt OK, I will try to do something about it on my free time. Publishing a library dedicated to that idea would be a very cool contribution to open-source world. Maybe you want to do that? Otherwise I'm going to try...
