### ISSUE TITLE
[Question] Any way to change appearance of status bar

### ISSUE THREAD

**Issue by BurhanDanger** [phillipberndt/pqiv#97]
Status bar seems good deal intrusive. It hide a portion of the image. Any way to hide it , or move it to bottom of the image.

**Comment by phillipberndt** [comment]
You can hide it using "i" or the "-i" option. The position is currently not
configurable, let me know if you'd like it to be.

**Comment by BurhanDanger** [comment]
Thanks, Any way to change default yellow colour , it pains my eyes.

**Comment by phillipberndt** [comment]
Sure. Use `--box-colors`. (In general: Have a look at the manpage, everything that is configurable is explained there.)

**Comment by BurhanDanger** [comment]
Oh it's called info box, sorry for bothering you. Will you implement xdg_config_home rather than home directory for pqivrc ?

**Comment by phillipberndt** [comment]
Sure thing. See the new bug I've opened - it contains a list of some things I'm uncertain about, I'd appreciate your (and others') opinion!
