### ISSUE TITLE
Load configuration from ~/.config/ and /etc/

### ISSUE THREAD

**Issue by phillipberndt** [phillipberndt/pqiv#98]
pqiv should:
* load the configuration from `${XDG_CONFIG_HOME:-${HOME}/.config}/pqivrc` if present
* load a system-wide configuration if present

open questions:
* Should the system-wide configuration file be in `${XDG_CONFIG_DIRS}/pqivrc` or `/etc/pqivrc`?
* What if multiple files are present? Load all of them or just one, prioritizing the user's local one?
* How to allow users to disable configuration file processing? (Important because the configuration can alter the meaning of command line parameters, making it important to disable configuration file processing when using pqiv from scripts. Currently, it suffices to unset `$HOME`.)

I'd tend to only process one configuration file, prioritizing ~/.config/pqivrc over ~/.pqivrc over /etc/whatever/pqivrc, and in addition giving the user a new command-line option to explicitly give a path to a configuration file to use.

See #97, cc @BurhanDanger.

**Comment by BurhanDanger** [comment]
1. System Wide Configuration : 
/etc/pqiv/config
or 
/usr/share/doc/pqiv/config
This is what I've seen other packages do.
2. Multiple config files -> most priority to users defined one.
You know it better. :)

**Comment by phillipberndt** [comment]
There's no need for an entire pqiv directory in `/etc`, so I went for `/etc/pqivrc`. This is in master now, final order of preference is:

* `$PQIVRC_PATH` from the environment; no further attempt to find any file is made if this variable is set
* `$XDG_CONFIG_HOME/pqivrc` if the variable is defined, `~/.config/pqivrc` otherwise
* `~/.pqivrc`
* A file named `pqivrc` within each directory defined in `$XDG_CONFIG_DIRS`
* `/etc/pqivrc`

At most one configuration file is processed.
