### ISSUE TITLE
Large zoom requires too much memory

### ISSUE THREAD

**Issue by amerlyq** [phillipberndt/pqiv#99]
Viewing large 5500x2700 pycallgraph.png on 400% zoom requires >1GB memory and it grows.
But `feh` works just fine, requiring no more then 200MB even on larger zoom levels.
Will it be possible to rework algorithms to enlarge only shown on screen part of image, as it done in feh?

**Comment by phillipberndt** [comment]
pqiv intentionally caches a scaled copy of the whole image to speed up movement in the zoomed image. You can change this behaviour using the command line option `--low-memory`. It will disable all sorts of caches and brings memory usage for a 5500x2700 image at 400% down to 115MiB on my system.

**Comment by amerlyq** [comment]
Thanks. From man it wasn't obvious, that `--low-memory` disables even zoom-caching beside disabling caching prev/next.

**Comment by phillipberndt** [comment]
FYI, I have found a way to *dramatically* increase performance for the case that used to be slow (moving a zoomed, rotated image around) in `--low-memory` mode. The change is now included in master.
